INSERT INTO exercises VALUES(1,'3/4 sit-up','abs');
INSERT INTO exercises VALUES(2,'45° side bend','abs');
INSERT INTO exercises VALUES(3,'air bike','abs');
INSERT INTO exercises VALUES(6,'alternate heel touchers','abs');
INSERT INTO exercises VALUES(7,'alternate lateral pulldown','lats');
INSERT INTO exercises VALUES(9,'assisted chest dip (kneeling)','pectorals');
INSERT INTO exercises VALUES(10,'assisted hanging knee raise with throw down','abs');
INSERT INTO exercises VALUES(11,'assisted hanging knee raise','abs');
INSERT INTO exercises VALUES(12,'assisted lying leg raise with lateral throw down','abs');
INSERT INTO exercises VALUES(13,'assisted lying leg raise with throw down','abs');
INSERT INTO exercises VALUES(14,'assisted motion russian twist','abs');
INSERT INTO exercises VALUES(15,'assisted parallel close grip pull-up','lats');
INSERT INTO exercises VALUES(16,'assisted prone hamstring','hamstrings');
INSERT INTO exercises VALUES(17,'assisted pull-up','lats');
INSERT INTO exercises VALUES(18,'assisted standing triceps extension (with towel)','triceps');
INSERT INTO exercises VALUES(19,'assisted triceps dip (kneeling)','triceps');
INSERT INTO exercises VALUES(20,'balance board','quads');
INSERT INTO exercises VALUES(22,'barbell pullover to press','lats');
INSERT INTO exercises VALUES(23,'barbell alternate biceps curl','biceps');
INSERT INTO exercises VALUES(24,'barbell bench front squat','quads');
INSERT INTO exercises VALUES(25,'barbell bench press','pectorals');
INSERT INTO exercises VALUES(26,'barbell bench squat','quads');
INSERT INTO exercises VALUES(27,'barbell bent over row','upper back');
INSERT INTO exercises VALUES(28,'barbell clean and press','quads');
INSERT INTO exercises VALUES(29,'barbell clean-grip front squat','glutes');
INSERT INTO exercises VALUES(30,'barbell close-grip bench press','triceps');
INSERT INTO exercises VALUES(31,'barbell curl','biceps');
INSERT INTO exercises VALUES(32,'barbell deadlift','glutes');
INSERT INTO exercises VALUES(33,'barbell decline bench press','pectorals');
INSERT INTO exercises VALUES(34,'barbell decline bent arm pullover','lats');
INSERT INTO exercises VALUES(35,'barbell decline close grip to skull press','triceps');
INSERT INTO exercises VALUES(36,'barbell decline wide-grip press','pectorals');
INSERT INTO exercises VALUES(37,'barbell decline wide-grip pullover','lats');
INSERT INTO exercises VALUES(38,'barbell drag curl','biceps');
INSERT INTO exercises VALUES(39,'barbell front chest squat','glutes');
INSERT INTO exercises VALUES(40,'barbell front raise and pullover','pectorals');
INSERT INTO exercises VALUES(41,'barbell front raise','delts');
INSERT INTO exercises VALUES(42,'barbell front squat','glutes');
INSERT INTO exercises VALUES(43,'barbell full squat','glutes');
INSERT INTO exercises VALUES(44,'barbell good morning','hamstrings');
INSERT INTO exercises VALUES(45,'barbell guillotine bench press','pectorals');
INSERT INTO exercises VALUES(46,'barbell hack squat','glutes');
INSERT INTO exercises VALUES(47,'barbell incline bench press','pectorals');
INSERT INTO exercises VALUES(48,'barbell incline reverse-grip press','triceps');
INSERT INTO exercises VALUES(49,'barbell incline row','upper back');
INSERT INTO exercises VALUES(50,'barbell incline shoulder raise','serratus anterior');
INSERT INTO exercises VALUES(51,'barbell jefferson squat','glutes');
INSERT INTO exercises VALUES(52,'barbell jm bench press','triceps');
INSERT INTO exercises VALUES(53,'barbell jump squat','glutes');
INSERT INTO exercises VALUES(54,'barbell lunge','glutes');
INSERT INTO exercises VALUES(55,'barbell lying close-grip press','triceps');
INSERT INTO exercises VALUES(56,'barbell lying close-grip triceps extension','triceps');
INSERT INTO exercises VALUES(57,'barbell lying extension','triceps');
INSERT INTO exercises VALUES(58,'barbell lying lifting (on hip)','glutes');
INSERT INTO exercises VALUES(59,'barbell lying preacher curl','biceps');
INSERT INTO exercises VALUES(60,'barbell lying triceps extension skull crusher','triceps');
INSERT INTO exercises VALUES(61,'barbell lying triceps extension','triceps');
INSERT INTO exercises VALUES(63,'barbell narrow stance squat','glutes');
INSERT INTO exercises VALUES(64,'barbell one arm bent over row','upper back');
INSERT INTO exercises VALUES(65,'barbell one arm floor press','triceps');
INSERT INTO exercises VALUES(66,'barbell one arm side deadlift','glutes');
INSERT INTO exercises VALUES(67,'barbell one arm snatch','delts');
INSERT INTO exercises VALUES(68,'barbell one leg squat','quads');
INSERT INTO exercises VALUES(69,'barbell overhead squat','quads');
INSERT INTO exercises VALUES(70,'barbell preacher curl','biceps');
INSERT INTO exercises VALUES(71,'barbell press sit-up','abs');
INSERT INTO exercises VALUES(72,'barbell prone incline curl','biceps');
INSERT INTO exercises VALUES(73,'barbell pullover','lats');
INSERT INTO exercises VALUES(74,'barbell rack pull','glutes');
INSERT INTO exercises VALUES(75,'barbell rear delt raise','delts');
INSERT INTO exercises VALUES(76,'barbell rear delt row','delts');
INSERT INTO exercises VALUES(77,'barbell rear lunge v. 2','glutes');
INSERT INTO exercises VALUES(78,'barbell rear lunge','glutes');
INSERT INTO exercises VALUES(79,'barbell revers wrist curl v. 2','forearms');
INSERT INTO exercises VALUES(80,'barbell reverse curl','biceps');
INSERT INTO exercises VALUES(81,'barbell reverse preacher curl','biceps');
INSERT INTO exercises VALUES(82,'barbell reverse wrist curl','forearms');
INSERT INTO exercises VALUES(83,'barbell rollerout from bench','abs');
INSERT INTO exercises VALUES(84,'barbell rollerout','abs');
INSERT INTO exercises VALUES(85,'barbell romanian deadlift','glutes');
INSERT INTO exercises VALUES(86,'barbell seated behind head military press','delts');
INSERT INTO exercises VALUES(87,'barbell seated bradford rocky press','delts');
INSERT INTO exercises VALUES(88,'barbell seated calf raise','calves');
INSERT INTO exercises VALUES(89,'barbell seated close-grip concentration curl','biceps');
INSERT INTO exercises VALUES(90,'barbell seated good morning','glutes');
INSERT INTO exercises VALUES(91,'barbell seated overhead press','delts');
INSERT INTO exercises VALUES(92,'barbell seated overhead triceps extension','triceps');
INSERT INTO exercises VALUES(94,'barbell seated twist','abs');
INSERT INTO exercises VALUES(95,'barbell shrug','traps');
INSERT INTO exercises VALUES(96,'barbell side bent v. 2','abs');
INSERT INTO exercises VALUES(97,'barbell side split squat v. 2','quads');
INSERT INTO exercises VALUES(98,'barbell side split squat','quads');
INSERT INTO exercises VALUES(99,'barbell single leg split squat','quads');
INSERT INTO exercises VALUES(100,'barbell skier','delts');
INSERT INTO exercises VALUES(101,'barbell speed squat','glutes');
INSERT INTO exercises VALUES(102,'barbell squat (on knees)','quads');
INSERT INTO exercises VALUES(103,'barbell standing ab rollerout','abs');
INSERT INTO exercises VALUES(104,'barbell standing back wrist curl','forearms');
INSERT INTO exercises VALUES(105,'barbell standing bradford press','delts');
INSERT INTO exercises VALUES(106,'barbell standing close grip curl','biceps');
INSERT INTO exercises VALUES(107,'barbell standing front raise over head','delts');
INSERT INTO exercises VALUES(108,'barbell standing leg calf raise','calves');
INSERT INTO exercises VALUES(109,'barbell standing overhead triceps extension','triceps');
INSERT INTO exercises VALUES(110,'barbell standing reverse grip curl','biceps');
INSERT INTO exercises VALUES(111,'barbell standing rocking leg calf raise','calves');
INSERT INTO exercises VALUES(112,'barbell standing twist','abs');
INSERT INTO exercises VALUES(113,'barbell standing wide-grip curl','biceps');
INSERT INTO exercises VALUES(114,'barbell step-up','glutes');
INSERT INTO exercises VALUES(115,'barbell stiff leg good morning','glutes');
INSERT INTO exercises VALUES(116,'barbell straight leg deadlift','hamstrings');
INSERT INTO exercises VALUES(117,'barbell sumo deadlift','glutes');
INSERT INTO exercises VALUES(118,'barbell reverse grip bent over row','upper back');
INSERT INTO exercises VALUES(119,'barbell upright row v. 2','delts');
INSERT INTO exercises VALUES(120,'barbell upright row','delts');
INSERT INTO exercises VALUES(121,'barbell upright row v. 3','delts');
INSERT INTO exercises VALUES(122,'barbell wide bench press','pectorals');
INSERT INTO exercises VALUES(123,'barbell wide-grip upright row','delts');
INSERT INTO exercises VALUES(124,'barbell wide squat','quads');
INSERT INTO exercises VALUES(125,'barbell wrist curl v. 2','forearms');
INSERT INTO exercises VALUES(126,'barbell wrist curl','forearms');
INSERT INTO exercises VALUES(127,'barbell zercher squat','glutes');
INSERT INTO exercises VALUES(128,'battling ropes','delts');
INSERT INTO exercises VALUES(129,'bench dip (knees bent)','triceps');
INSERT INTO exercises VALUES(130,'bench hip extension','glutes');
INSERT INTO exercises VALUES(137,'body-up','triceps');
INSERT INTO exercises VALUES(138,'bottoms-up','abs');
INSERT INTO exercises VALUES(139,'biceps narrow pull-ups','biceps');
INSERT INTO exercises VALUES(140,'biceps pull-up','biceps');
INSERT INTO exercises VALUES(148,'cable alternate shoulder press','delts');
INSERT INTO exercises VALUES(149,'cable alternate triceps extension','triceps');
INSERT INTO exercises VALUES(150,'cable bar lateral pulldown','lats');
INSERT INTO exercises VALUES(151,'cable bench press','pectorals');
INSERT INTO exercises VALUES(152,'cable concentration extension (on knee)','triceps');
INSERT INTO exercises VALUES(153,'cable cross-over lateral pulldown','lats');
INSERT INTO exercises VALUES(154,'cable cross-over revers fly','delts');
INSERT INTO exercises VALUES(155,'cable cross-over variation','pectorals');
INSERT INTO exercises VALUES(157,'cable deadlift','glutes');
INSERT INTO exercises VALUES(158,'cable decline fly','pectorals');
INSERT INTO exercises VALUES(159,'cable decline seated wide-grip row','upper back');
INSERT INTO exercises VALUES(160,'cable floor seated wide-grip row','upper back');
INSERT INTO exercises VALUES(161,'cable forward raise','delts');
INSERT INTO exercises VALUES(162,'cable front raise','delts');
INSERT INTO exercises VALUES(164,'cable front shoulder raise','delts');
INSERT INTO exercises VALUES(165,'cable hammer curl (with rope)','biceps');
INSERT INTO exercises VALUES(167,'cable high row (kneeling)','upper back');
INSERT INTO exercises VALUES(168,'cable hip adduction','adductors');
INSERT INTO exercises VALUES(169,'cable incline bench press','pectorals');
INSERT INTO exercises VALUES(170,'cable incline fly (on stability ball)','pectorals');
INSERT INTO exercises VALUES(171,'cable incline fly','pectorals');
INSERT INTO exercises VALUES(172,'cable incline pushdown','lats');
INSERT INTO exercises VALUES(173,'cable incline triceps extension','triceps');
INSERT INTO exercises VALUES(174,'cable judo flip','abs');
INSERT INTO exercises VALUES(175,'cable kneeling crunch','abs');
INSERT INTO exercises VALUES(176,'cable kneeling triceps extension','triceps');
INSERT INTO exercises VALUES(177,'cable lateral pulldown (with rope attachment)','lats');
INSERT INTO exercises VALUES(178,'cable lateral raise','delts');
INSERT INTO exercises VALUES(179,'cable low fly','pectorals');
INSERT INTO exercises VALUES(180,'cable low seated row','upper back');
INSERT INTO exercises VALUES(182,'cable lying close-grip curl','biceps');
INSERT INTO exercises VALUES(184,'cable lying extension pullover (with rope attachment)','lats');
INSERT INTO exercises VALUES(185,'cable lying fly','pectorals');
INSERT INTO exercises VALUES(186,'cable lying triceps extension v. 2','triceps');
INSERT INTO exercises VALUES(188,'cable middle fly','pectorals');
INSERT INTO exercises VALUES(189,'cable one arm bent over row','upper back');
INSERT INTO exercises VALUES(190,'cable one arm curl','biceps');
INSERT INTO exercises VALUES(191,'cable one arm lateral bent-over','pectorals');
INSERT INTO exercises VALUES(192,'cable one arm lateral raise','delts');
INSERT INTO exercises VALUES(193,'cable one arm straight back high row (kneeling)','upper back');
INSERT INTO exercises VALUES(194,'cable overhead triceps extension (rope attachment)','triceps');
INSERT INTO exercises VALUES(195,'cable preacher curl','biceps');
INSERT INTO exercises VALUES(196,'cable pull through (with rope)','glutes');
INSERT INTO exercises VALUES(197,'cable pulldown (pro lat bar)','lats');
INSERT INTO exercises VALUES(198,'cable pulldown','lats');
INSERT INTO exercises VALUES(199,'cable pushdown (straight arm) v. 2','lats');
INSERT INTO exercises VALUES(200,'cable pushdown (with rope attachment)','triceps');
INSERT INTO exercises VALUES(201,'cable pushdown','triceps');
INSERT INTO exercises VALUES(202,'cable rear delt row (stirrups)','delts');
INSERT INTO exercises VALUES(203,'cable rear delt row (with rope)','delts');
INSERT INTO exercises VALUES(204,'cable rear drive','triceps');
INSERT INTO exercises VALUES(205,'cable rear pulldown','lats');
INSERT INTO exercises VALUES(206,'cable reverse curl','biceps');
INSERT INTO exercises VALUES(207,'cable reverse-grip pushdown','triceps');
INSERT INTO exercises VALUES(208,'cable reverse-grip straight back seated high row','upper back');
INSERT INTO exercises VALUES(209,'cable reverse preacher curl','biceps');
INSERT INTO exercises VALUES(210,'cable reverse wrist curl','forearms');
INSERT INTO exercises VALUES(211,'cable russian twists (on stability ball)','abs');
INSERT INTO exercises VALUES(212,'cable seated crunch','abs');
INSERT INTO exercises VALUES(213,'cable seated high row (v-bar)','lats');
INSERT INTO exercises VALUES(214,'cable seated one arm alternate row','upper back');
INSERT INTO exercises VALUES(215,'cable seated rear lateral raise','delts');
INSERT INTO exercises VALUES(216,'cable seated shoulder internal rotation','delts');
INSERT INTO exercises VALUES(218,'cable seated wide-grip row','upper back');
INSERT INTO exercises VALUES(219,'cable shoulder press','delts');
INSERT INTO exercises VALUES(220,'cable shrug','traps');
INSERT INTO exercises VALUES(221,'cable side bend crunch (bosu ball)','abs');
INSERT INTO exercises VALUES(222,'cable side bend','abs');
INSERT INTO exercises VALUES(223,'cable side crunch','abs');
INSERT INTO exercises VALUES(224,'cable standing back wrist curl','forearms');
INSERT INTO exercises VALUES(225,'cable standing cross-over high reverse fly','delts');
INSERT INTO exercises VALUES(226,'cable standing crunch','abs');
INSERT INTO exercises VALUES(227,'cable standing fly','pectorals');
INSERT INTO exercises VALUES(228,'cable standing hip extension','glutes');
INSERT INTO exercises VALUES(229,'cable standing inner curl','biceps');
INSERT INTO exercises VALUES(230,'cable standing lift','abs');
INSERT INTO exercises VALUES(231,'cable standing one arm triceps extension','triceps');
INSERT INTO exercises VALUES(232,'cable standing pulldown (with rope)','biceps');
INSERT INTO exercises VALUES(233,'cable standing rear delt row (with rope)','delts');
INSERT INTO exercises VALUES(234,'cable standing row (v-bar)','upper back');
INSERT INTO exercises VALUES(235,'cable standing shoulder external rotation','delts');
INSERT INTO exercises VALUES(236,'cable standing twist row (v-bar)','upper back');
INSERT INTO exercises VALUES(237,'cable straight arm pulldown (with rope)','lats');
INSERT INTO exercises VALUES(238,'cable straight arm pulldown','lats');
INSERT INTO exercises VALUES(239,'cable straight back seated row','upper back');
INSERT INTO exercises VALUES(240,'cable supine reverse fly','delts');
INSERT INTO exercises VALUES(241,'cable triceps pushdown (v-bar)','triceps');
INSERT INTO exercises VALUES(242,'cable tuck reverse crunch','abs');
INSERT INTO exercises VALUES(243,'cable twist','abs');
INSERT INTO exercises VALUES(244,'cable twisting pull','lats');
INSERT INTO exercises VALUES(245,'cable underhand pulldown','lats');
INSERT INTO exercises VALUES(246,'cable upright row','delts');
INSERT INTO exercises VALUES(247,'cable wrist curl','forearms');
INSERT INTO exercises VALUES(248,'cambered bar lying row','upper back');
INSERT INTO exercises VALUES(251,'chest dip','pectorals');
INSERT INTO exercises VALUES(253,'chin-ups (narrow parallel grip)','upper back');
INSERT INTO exercises VALUES(257,'circles knee stretch','calves');
INSERT INTO exercises VALUES(258,'clock push-up','pectorals');
INSERT INTO exercises VALUES(259,'close-grip push-up','triceps');
INSERT INTO exercises VALUES(260,'cocoons','abs');
INSERT INTO exercises VALUES(262,'cross body crunch','abs');
INSERT INTO exercises VALUES(267,'crunch (hands overhead)','abs');
INSERT INTO exercises VALUES(271,'crunch (on stability ball)','abs');
INSERT INTO exercises VALUES(272,'crunch (on stability ball, arms straight)','abs');
INSERT INTO exercises VALUES(274,'crunch floor','abs');
INSERT INTO exercises VALUES(276,'dead bug','abs');
INSERT INTO exercises VALUES(277,'decline crunch','abs');
INSERT INTO exercises VALUES(279,'decline push-up','pectorals');
INSERT INTO exercises VALUES(282,'decline sit-up','abs');
INSERT INTO exercises VALUES(283,'diamond push-up','triceps');
INSERT INTO exercises VALUES(284,'donkey calf raise','calves');
INSERT INTO exercises VALUES(285,'dumbbell alternate biceps curl','biceps');
INSERT INTO exercises VALUES(286,'dumbbell alternate side press','delts');
INSERT INTO exercises VALUES(287,'dumbbell arnold press v. 2','delts');
INSERT INTO exercises VALUES(288,'dumbbell around pullover','pectorals');
INSERT INTO exercises VALUES(289,'dumbbell bench press','pectorals');
INSERT INTO exercises VALUES(290,'dumbbell bench seated press','delts');
INSERT INTO exercises VALUES(291,'dumbbell bench squat','glutes');
INSERT INTO exercises VALUES(292,'dumbbell one arm bent-over row','upper back');
INSERT INTO exercises VALUES(293,'dumbbell bent over row','upper back');
INSERT INTO exercises VALUES(294,'dumbbell biceps curl','biceps');
INSERT INTO exercises VALUES(295,'dumbbell clean','glutes');
INSERT INTO exercises VALUES(296,'dumbbell close-grip press','triceps');
INSERT INTO exercises VALUES(297,'dumbbell concentration curl','biceps');
INSERT INTO exercises VALUES(298,'dumbbell cross body hammer curl','biceps');
INSERT INTO exercises VALUES(299,'dumbbell cuban press','delts');
INSERT INTO exercises VALUES(300,'dumbbell deadlift','glutes');
INSERT INTO exercises VALUES(301,'dumbbell decline bench press','pectorals');
INSERT INTO exercises VALUES(302,'dumbbell decline fly','pectorals');
INSERT INTO exercises VALUES(303,'dumbbell decline hammer press','pectorals');
INSERT INTO exercises VALUES(304,'dumbbell decline shrug v. 2','traps');
INSERT INTO exercises VALUES(305,'dumbbell decline shrug','traps');
INSERT INTO exercises VALUES(306,'dumbbell decline triceps extension','triceps');
INSERT INTO exercises VALUES(307,'dumbbell decline twist fly','pectorals');
INSERT INTO exercises VALUES(308,'dumbbell fly','pectorals');
INSERT INTO exercises VALUES(309,'dumbbell front raise v. 2','delts');
INSERT INTO exercises VALUES(310,'dumbbell front raise','delts');
INSERT INTO exercises VALUES(311,'dumbbell full can lateral raise','delts');
INSERT INTO exercises VALUES(312,'dumbbell hammer curl v. 2','biceps');
INSERT INTO exercises VALUES(313,'dumbbell hammer curl','biceps');
INSERT INTO exercises VALUES(314,'dumbbell incline bench press','pectorals');
INSERT INTO exercises VALUES(315,'dumbbell incline biceps curl','biceps');
INSERT INTO exercises VALUES(316,'dumbbell incline breeding','pectorals');
INSERT INTO exercises VALUES(317,'dumbbell incline curl v. 2','biceps');
INSERT INTO exercises VALUES(318,'dumbbell incline curl','biceps');
INSERT INTO exercises VALUES(319,'dumbbell incline fly','pectorals');
INSERT INTO exercises VALUES(320,'dumbbell incline hammer curl','biceps');
INSERT INTO exercises VALUES(321,'dumbbell incline hammer press','pectorals');
INSERT INTO exercises VALUES(322,'dumbbell incline inner biceps curl','biceps');
INSERT INTO exercises VALUES(323,'dumbbell incline one arm lateral raise','delts');
INSERT INTO exercises VALUES(324,'dumbbell incline palm-in press','pectorals');
INSERT INTO exercises VALUES(325,'dumbbell incline raise','delts');
INSERT INTO exercises VALUES(326,'dumbbell incline rear lateral raise','delts');
INSERT INTO exercises VALUES(327,'dumbbell incline row','upper back');
INSERT INTO exercises VALUES(328,'dumbbell incline shoulder raise','serratus anterior');
INSERT INTO exercises VALUES(329,'dumbbell incline shrug','traps');
INSERT INTO exercises VALUES(330,'dumbbell incline triceps extension','triceps');
INSERT INTO exercises VALUES(331,'dumbbell incline twisted flyes','pectorals');
INSERT INTO exercises VALUES(332,'dumbbell iron cross','delts');
INSERT INTO exercises VALUES(333,'dumbbell kickback','triceps');
INSERT INTO exercises VALUES(334,'dumbbell lateral raise','delts');
INSERT INTO exercises VALUES(335,'dumbbell lateral to front raise','delts');
INSERT INTO exercises VALUES(336,'dumbbell lunge','glutes');
INSERT INTO exercises VALUES(337,'dumbbell lying  extension (across face)','triceps');
INSERT INTO exercises VALUES(338,'dumbbell lying elbow press','triceps');
INSERT INTO exercises VALUES(339,'dumbbell lying femoral','hamstrings');
INSERT INTO exercises VALUES(340,'dumbbell lying hammer press','pectorals');
INSERT INTO exercises VALUES(341,'dumbbell lying one arm deltoid rear','delts');
INSERT INTO exercises VALUES(342,'dumbbell lying one arm press v. 2','pectorals');
INSERT INTO exercises VALUES(343,'dumbbell lying one arm press','pectorals');
INSERT INTO exercises VALUES(344,'dumbbell lying one arm pronated triceps extension','triceps');
INSERT INTO exercises VALUES(345,'dumbbell lying one arm rear lateral raise','delts');
INSERT INTO exercises VALUES(346,'dumbbell lying one arm supinated triceps extension','triceps');
INSERT INTO exercises VALUES(347,'dumbbell lying pronation','forearms');
INSERT INTO exercises VALUES(348,'dumbbell lying rear lateral raise','delts');
INSERT INTO exercises VALUES(349,'dumbbell lying supination','forearms');
INSERT INTO exercises VALUES(350,'dumbbell lying supine curl','biceps');
INSERT INTO exercises VALUES(351,'dumbbell lying triceps extension','triceps');
INSERT INTO exercises VALUES(352,'dumbbell neutral grip bench press','triceps');
INSERT INTO exercises VALUES(353,'dumbbell one arm concetration curl (on stability ball)','biceps');
INSERT INTO exercises VALUES(354,'dumbbell one arm kickback','triceps');
INSERT INTO exercises VALUES(355,'dumbbell one arm lateral raise','delts');
INSERT INTO exercises VALUES(356,'dumbbell one arm lateral raise with support','delts');
INSERT INTO exercises VALUES(358,'dumbbell one arm revers wrist curl','forearms');
INSERT INTO exercises VALUES(359,'dumbbell one arm reverse fly (with support)','delts');
INSERT INTO exercises VALUES(360,'dumbbell one arm shoulder press v. 2','delts');
INSERT INTO exercises VALUES(361,'dumbbell one arm shoulder press','delts');
INSERT INTO exercises VALUES(362,'dumbbell one arm triceps extension (on bench)','triceps');
INSERT INTO exercises VALUES(363,'dumbbell one arm upright row','delts');
INSERT INTO exercises VALUES(364,'dumbbell one arm wrist curl','forearms');
INSERT INTO exercises VALUES(365,'dumbbell over bench neutral wrist curl','biceps');
INSERT INTO exercises VALUES(366,'dumbbell over bench one arm  neutral wrist curl','biceps');
INSERT INTO exercises VALUES(367,'dumbbell over bench one arm wrist curl','forearms');
INSERT INTO exercises VALUES(368,'dumbbell over bench revers wrist curl','forearms');
INSERT INTO exercises VALUES(369,'dumbbell over bench wrist curl','forearms');
INSERT INTO exercises VALUES(370,'dumbbell peacher hammer curl','biceps');
INSERT INTO exercises VALUES(371,'dumbbell plyo squat','glutes');
INSERT INTO exercises VALUES(372,'dumbbell preacher curl','biceps');
INSERT INTO exercises VALUES(373,'dumbbell pronate-grip triceps extension','triceps');
INSERT INTO exercises VALUES(374,'dumbbell prone incline curl','biceps');
INSERT INTO exercises VALUES(375,'dumbbell pullover','pectorals');
INSERT INTO exercises VALUES(376,'dumbbell raise','delts');
INSERT INTO exercises VALUES(377,'dumbbell rear delt row_shoulder','delts');
INSERT INTO exercises VALUES(378,'dumbbell rear fly','delts');
INSERT INTO exercises VALUES(379,'dumbbell rear lateral raise (support head)','delts');
INSERT INTO exercises VALUES(380,'dumbbell rear lateral raise','delts');
INSERT INTO exercises VALUES(381,'dumbbell rear lunge','glutes');
INSERT INTO exercises VALUES(382,'dumbbell revers grip biceps curl','biceps');
INSERT INTO exercises VALUES(383,'dumbbell reverse fly','delts');
INSERT INTO exercises VALUES(384,'dumbbell reverse preacher curl','biceps');
INSERT INTO exercises VALUES(385,'dumbbell reverse wrist curl','forearms');
INSERT INTO exercises VALUES(386,'dumbbell rotation reverse fly','delts');
INSERT INTO exercises VALUES(387,'dumbbell seated alternate front raise','delts');
INSERT INTO exercises VALUES(388,'dumbbell seated alternate press','delts');
INSERT INTO exercises VALUES(389,'dumbbell seated bench extension','triceps');
INSERT INTO exercises VALUES(390,'dumbbell seated biceps curl (on stability ball)','biceps');
INSERT INTO exercises VALUES(391,'dumbbell seated curl','biceps');
INSERT INTO exercises VALUES(392,'dumbbell seated front raise','delts');
INSERT INTO exercises VALUES(393,'dumbbell seated inner biceps curl','biceps');
INSERT INTO exercises VALUES(394,'dumbbell seated kickback','triceps');
INSERT INTO exercises VALUES(395,'dumbbell seated lateral raise v. 2','delts');
INSERT INTO exercises VALUES(396,'dumbbell seated lateral raise','delts');
INSERT INTO exercises VALUES(397,'dumbbell seated neutral wrist curl','biceps');
INSERT INTO exercises VALUES(398,'dumbbell seated one arm kickback','triceps');
INSERT INTO exercises VALUES(399,'dumbbell seated one arm rotate','forearms');
INSERT INTO exercises VALUES(400,'dumbbell seated one leg calf raise','calves');
INSERT INTO exercises VALUES(401,'dumbbell seated palms up wrist curl','forearms');
INSERT INTO exercises VALUES(402,'dumbbell seated preacher curl','biceps');
INSERT INTO exercises VALUES(403,'dumbbell seated revers grip concentration curl','biceps');
INSERT INTO exercises VALUES(404,'dumbbell seated shoulder press (parallel grip)','delts');
INSERT INTO exercises VALUES(405,'dumbbell seated shoulder press','delts');
INSERT INTO exercises VALUES(406,'dumbbell shrug','traps');
INSERT INTO exercises VALUES(407,'dumbbell side bend','abs');
INSERT INTO exercises VALUES(408,'dumbbell side lying one hand raise','delts');
INSERT INTO exercises VALUES(409,'dumbbell single leg calf raise','calves');
INSERT INTO exercises VALUES(410,'dumbbell single leg split squat','quads');
INSERT INTO exercises VALUES(411,'dumbbell single leg squat','glutes');
INSERT INTO exercises VALUES(413,'dumbbell squat','glutes');
INSERT INTO exercises VALUES(414,'dumbbell standing alternate overhead press','delts');
INSERT INTO exercises VALUES(415,'dumbbell standing alternate raise','delts');
INSERT INTO exercises VALUES(416,'dumbbell standing biceps curl','biceps');
INSERT INTO exercises VALUES(417,'dumbbell standing calf raise','calves');
INSERT INTO exercises VALUES(418,'dumbbell standing concentration curl','biceps');
INSERT INTO exercises VALUES(419,'dumbbell standing front raise above head','delts');
INSERT INTO exercises VALUES(420,'dumbbell standing kickback','triceps');
INSERT INTO exercises VALUES(421,'dumbbell standing one arm concentration curl','biceps');
INSERT INTO exercises VALUES(422,'dumbbell standing one arm curl (over incline bench)','biceps');
INSERT INTO exercises VALUES(423,'dumbbell standing one arm extension','triceps');
INSERT INTO exercises VALUES(424,'dumbbell standing one arm palm in press','delts');
INSERT INTO exercises VALUES(425,'dumbbell standing one arm reverse curl','biceps');
INSERT INTO exercises VALUES(426,'dumbbell standing overhead press','delts');
INSERT INTO exercises VALUES(427,'dumbbell standing palms in press','delts');
INSERT INTO exercises VALUES(428,'dumbbell standing preacher curl','biceps');
INSERT INTO exercises VALUES(429,'dumbbell standing reverse curl','biceps');
INSERT INTO exercises VALUES(430,'dumbbell standing triceps extension','triceps');
INSERT INTO exercises VALUES(431,'dumbbell step-up','glutes');
INSERT INTO exercises VALUES(432,'dumbbell stiff leg deadlift','glutes');
INSERT INTO exercises VALUES(433,'dumbbell straight arm pullover','pectorals');
INSERT INTO exercises VALUES(434,'dumbbell straight leg deadlift','glutes');
INSERT INTO exercises VALUES(436,'dumbbell tate press','triceps');
INSERT INTO exercises VALUES(437,'dumbbell upright row','delts');
INSERT INTO exercises VALUES(438,'dumbbell w-press','delts');
INSERT INTO exercises VALUES(439,'dumbbell zottman curl','biceps');
INSERT INTO exercises VALUES(443,'elbow-to-knee','abs');
INSERT INTO exercises VALUES(445,'ez barbell anti gravity press','delts');
INSERT INTO exercises VALUES(446,'ez barbell close-grip curl','biceps');
INSERT INTO exercises VALUES(447,'ez barbell curl','biceps');
INSERT INTO exercises VALUES(448,'ez barbell decline close grip face press','triceps');
INSERT INTO exercises VALUES(449,'ez barbell incline triceps extension','triceps');
INSERT INTO exercises VALUES(450,'ez barbell jm bench press','triceps');
INSERT INTO exercises VALUES(451,'ez barbell reverse grip curl','biceps');
INSERT INTO exercises VALUES(452,'ez barbell reverse grip preacher curl','biceps');
INSERT INTO exercises VALUES(453,'ez barbell seated triceps extension','triceps');
INSERT INTO exercises VALUES(454,'ez barbell spider curl','biceps');
INSERT INTO exercises VALUES(455,'finger curls','forearms');
INSERT INTO exercises VALUES(456,'flexion leg sit up (bent knee)','abs');
INSERT INTO exercises VALUES(457,'flexion leg sit up (straight arm)','abs');
INSERT INTO exercises VALUES(458,'floor fly (with barbell)','pectorals');
INSERT INTO exercises VALUES(459,'flutter kicks','glutes');
INSERT INTO exercises VALUES(464,'front plank with twist','abs');
INSERT INTO exercises VALUES(466,'gironda sternum chin','lats');
INSERT INTO exercises VALUES(467,'gorilla chin','abs');
INSERT INTO exercises VALUES(469,'groin crunch','abs');
INSERT INTO exercises VALUES(471,'handstand push-up','triceps');
INSERT INTO exercises VALUES(472,'hanging leg raise','abs');
INSERT INTO exercises VALUES(473,'hanging pike','abs');
INSERT INTO exercises VALUES(474,'hanging straight leg hip raise','abs');
INSERT INTO exercises VALUES(475,'hanging straight leg raise','abs');
INSERT INTO exercises VALUES(476,'hanging straight twisting leg hip raise','abs');
INSERT INTO exercises VALUES(484,'hip raise (bent knee)','abs');
INSERT INTO exercises VALUES(488,'hyperextension (on bench)','spine');
INSERT INTO exercises VALUES(489,'hyperextension','spine');
INSERT INTO exercises VALUES(490,'incline close-grip push-up','triceps');
INSERT INTO exercises VALUES(491,'incline leg hip raise (leg straight)','abs');
INSERT INTO exercises VALUES(492,'incline push up depth jump','pectorals');
INSERT INTO exercises VALUES(493,'incline push-up','pectorals');
INSERT INTO exercises VALUES(494,'incline reverse grip push-up','pectorals');
INSERT INTO exercises VALUES(495,'incline twisting sit-up','abs');
INSERT INTO exercises VALUES(496,'inverse leg curl (bench support)','hamstrings');
INSERT INTO exercises VALUES(497,'inverted row v. 2','upper back');
INSERT INTO exercises VALUES(498,'inverted row with straps','upper back');
INSERT INTO exercises VALUES(499,'inverted row','upper back');
INSERT INTO exercises VALUES(500,'isometric wipers','pectorals');
INSERT INTO exercises VALUES(501,'jack burpee','cardiovascular system');
INSERT INTO exercises VALUES(507,'jackknife sit-up','abs');
INSERT INTO exercises VALUES(508,'janda sit-up','abs');
INSERT INTO exercises VALUES(513,'jump squat v. 2','glutes');
INSERT INTO exercises VALUES(514,'jump squat','glutes');
INSERT INTO exercises VALUES(517,'kettlebell advanced windmill','abs');
INSERT INTO exercises VALUES(518,'kettlebell alternating hang clean','forearms');
INSERT INTO exercises VALUES(519,'kettlebell alternating press on floor','pectorals');
INSERT INTO exercises VALUES(520,'kettlebell alternating press','delts');
INSERT INTO exercises VALUES(521,'kettlebell alternating renegade row','upper back');
INSERT INTO exercises VALUES(522,'kettlebell alternating row','upper back');
INSERT INTO exercises VALUES(523,'kettlebell arnold press','delts');
INSERT INTO exercises VALUES(524,'kettlebell bent press','abs');
INSERT INTO exercises VALUES(525,'kettlebell bottoms up clean from the hang position','biceps');
INSERT INTO exercises VALUES(526,'kettlebell double alternating hang clean','biceps');
INSERT INTO exercises VALUES(527,'kettlebell double jerk','delts');
INSERT INTO exercises VALUES(528,'kettlebell double push press','delts');
INSERT INTO exercises VALUES(529,'kettlebell double snatch','delts');
INSERT INTO exercises VALUES(530,'kettlebell double windmill','abs');
INSERT INTO exercises VALUES(531,'kettlebell extended range one arm press on floor','pectorals');
INSERT INTO exercises VALUES(532,'kettlebell figure 8','abs');
INSERT INTO exercises VALUES(533,'kettlebell front squat','glutes');
INSERT INTO exercises VALUES(534,'kettlebell goblet squat','glutes');
INSERT INTO exercises VALUES(535,'kettlebell hang clean','hamstrings');
INSERT INTO exercises VALUES(536,'kettlebell lunge pass through','glutes');
INSERT INTO exercises VALUES(537,'kettlebell one arm clean and jerk','delts');
INSERT INTO exercises VALUES(538,'kettlebell one arm jerk','delts');
INSERT INTO exercises VALUES(539,'kettlebell one arm military press to the side','delts');
INSERT INTO exercises VALUES(540,'kettlebell one arm push press','delts');
INSERT INTO exercises VALUES(541,'kettlebell one arm row','upper back');
INSERT INTO exercises VALUES(542,'kettlebell one arm snatch','delts');
INSERT INTO exercises VALUES(543,'kettlebell pirate supper legs','delts');
INSERT INTO exercises VALUES(544,'kettlebell pistol squat','glutes');
INSERT INTO exercises VALUES(545,'kettlebell plyo push-up','pectorals');
INSERT INTO exercises VALUES(546,'kettlebell seated press','delts');
INSERT INTO exercises VALUES(547,'kettlebell seesaw press','delts');
INSERT INTO exercises VALUES(548,'kettlebell sumo high pull','traps');
INSERT INTO exercises VALUES(549,'kettlebell swing','glutes');
INSERT INTO exercises VALUES(550,'kettlebell thruster','delts');
INSERT INTO exercises VALUES(551,'kettlebell turkish get up (squat style)','glutes');
INSERT INTO exercises VALUES(552,'kettlebell two arm clean','delts');
INSERT INTO exercises VALUES(553,'kettlebell two arm military press','delts');
INSERT INTO exercises VALUES(554,'kettlebell windmill','abs');
INSERT INTO exercises VALUES(555,'kick out sit','hamstrings');
INSERT INTO exercises VALUES(558,'kipping muscle up','lats');
INSERT INTO exercises VALUES(562,'landmine 180','abs');
INSERT INTO exercises VALUES(570,'leg pull in flat bench','abs');
INSERT INTO exercises VALUES(571,'lever alternating narrow grip seated row ','upper back');
INSERT INTO exercises VALUES(572,'lever assisted chin-up','lats');
INSERT INTO exercises VALUES(573,'lever back extension','spine');
INSERT INTO exercises VALUES(574,'lever bent over row ','upper back');
INSERT INTO exercises VALUES(575,'lever bicep curl','biceps');
INSERT INTO exercises VALUES(576,'lever chest press ','pectorals');
INSERT INTO exercises VALUES(577,'lever chest press','pectorals');
INSERT INTO exercises VALUES(578,'lever deadlift ','glutes');
INSERT INTO exercises VALUES(579,'lever front pulldown','lats');
INSERT INTO exercises VALUES(580,'lever gripless shrug','traps');
INSERT INTO exercises VALUES(581,'lever high row ','upper back');
INSERT INTO exercises VALUES(582,'lever kneeling leg curl ','hamstrings');
INSERT INTO exercises VALUES(583,'lever kneeling twist','abs');
INSERT INTO exercises VALUES(584,'lever lateral raise','delts');
INSERT INTO exercises VALUES(585,'lever leg extension','quads');
INSERT INTO exercises VALUES(586,'lever lying leg curl','hamstrings');
INSERT INTO exercises VALUES(587,'lever military press ','delts');
INSERT INTO exercises VALUES(588,'lever narrow grip seated row ','upper back');
INSERT INTO exercises VALUES(589,'lever one arm bent over row ','upper back');
INSERT INTO exercises VALUES(590,'lever one arm shoulder press ','delts');
INSERT INTO exercises VALUES(591,'lever overhand triceps dip','triceps');
INSERT INTO exercises VALUES(592,'lever preacher curl','biceps');
INSERT INTO exercises VALUES(593,'lever reverse hyperextension ','glutes');
INSERT INTO exercises VALUES(594,'lever seated calf raise ','calves');
INSERT INTO exercises VALUES(595,'lever seated crunch (chest pad)','abs');
INSERT INTO exercises VALUES(596,'lever seated fly','pectorals');
INSERT INTO exercises VALUES(597,'lever seated hip abduction','abductors');
INSERT INTO exercises VALUES(598,'lever seated hip adduction','adductors');
INSERT INTO exercises VALUES(599,'lever seated leg curl','hamstrings');
INSERT INTO exercises VALUES(600,'lever seated leg raise crunch ','abs');
INSERT INTO exercises VALUES(601,'lever seated reverse fly (parallel grip)','delts');
INSERT INTO exercises VALUES(602,'lever seated reverse fly','delts');
INSERT INTO exercises VALUES(603,'lever shoulder press ','delts');
INSERT INTO exercises VALUES(604,'lever shrug ','traps');
INSERT INTO exercises VALUES(605,'lever standing calf raise','calves');
INSERT INTO exercises VALUES(606,'lever t bar row ','upper back');
INSERT INTO exercises VALUES(607,'lever triceps extension','triceps');
INSERT INTO exercises VALUES(609,'london bridge','upper back');
INSERT INTO exercises VALUES(613,'lying (side) quads stretch','quads');
INSERT INTO exercises VALUES(620,'lying leg raise flat bench','abs');
INSERT INTO exercises VALUES(624,'march sit (wall)','glutes');
INSERT INTO exercises VALUES(627,'mixed grip chin-up','lats');
INSERT INTO exercises VALUES(628,'monster walk','glutes');
INSERT INTO exercises VALUES(630,'mountain climber','cardiovascular system');
INSERT INTO exercises VALUES(631,'muscle up','lats');
INSERT INTO exercises VALUES(634,'negative crunch','abs');
INSERT INTO exercises VALUES(635,'oblique crunches floor','abs');
INSERT INTO exercises VALUES(636,'olympic barbell hammer curl','biceps');
INSERT INTO exercises VALUES(637,'olympic barbell triceps extension','triceps');
INSERT INTO exercises VALUES(638,'one arm chin-up','lats');
INSERT INTO exercises VALUES(639,'one arm dip','triceps');
INSERT INTO exercises VALUES(640,'one arm slam (with medicine ball)','abs');
INSERT INTO exercises VALUES(641,'otis up','abs');
INSERT INTO exercises VALUES(642,'outside leg kick push-up','glutes');
INSERT INTO exercises VALUES(643,'overhead triceps stretch','triceps');
INSERT INTO exercises VALUES(648,'power clean','hamstrings');
INSERT INTO exercises VALUES(650,'pull-in (on stability ball)','abs');
INSERT INTO exercises VALUES(651,'pull up (neutral grip)','lats');
INSERT INTO exercises VALUES(652,'pull-up','lats');
INSERT INTO exercises VALUES(653,'push-up (bosu ball)','pectorals');
INSERT INTO exercises VALUES(655,'push-up (on stability ball)','pectorals');
INSERT INTO exercises VALUES(656,'push-up (on stability ball)','pectorals');
INSERT INTO exercises VALUES(658,'push-up (wall) v. 2','pectorals');
INSERT INTO exercises VALUES(659,'push-up (wall)','pectorals');
INSERT INTO exercises VALUES(660,'push-up close-grip off dumbbell','triceps');
INSERT INTO exercises VALUES(661,'push-up inside leg kick','glutes');
INSERT INTO exercises VALUES(662,'push-up','pectorals');
INSERT INTO exercises VALUES(663,'push-up medicine ball','pectorals');
INSERT INTO exercises VALUES(664,'push-up to side plank','abs');
INSERT INTO exercises VALUES(666,'raise single arm push-up','pectorals');
INSERT INTO exercises VALUES(668,'rear decline bridge','glutes');
INSERT INTO exercises VALUES(669,'rear deltoid stretch','delts');
INSERT INTO exercises VALUES(670,'rear pull-up','lats');
INSERT INTO exercises VALUES(672,'reverse dip','triceps');
INSERT INTO exercises VALUES(673,'reverse grip machine lat pulldown','lats');
INSERT INTO exercises VALUES(674,'reverse grip pull-up','lats');
INSERT INTO exercises VALUES(675,'reverse hyper extension (on stability ball)','glutes');
INSERT INTO exercises VALUES(677,'ring dips','triceps');
INSERT INTO exercises VALUES(678,'rocky pull-up pulldown','lats');
INSERT INTO exercises VALUES(680,'rope climb','upper back');
INSERT INTO exercises VALUES(684,'run (equipment)','cardiovascular system');
INSERT INTO exercises VALUES(685,'run','cardiovascular system');
INSERT INTO exercises VALUES(687,'russian twist','abs');
INSERT INTO exercises VALUES(688,'scapular pull-up','traps');
INSERT INTO exercises VALUES(689,'seated leg raise','abs');
INSERT INTO exercises VALUES(690,'seated lower back stretch','lats');
INSERT INTO exercises VALUES(691,'seated side crunch (wall)','abs');
INSERT INTO exercises VALUES(696,'self assisted inverse leg curl (on floor)','hamstrings');
INSERT INTO exercises VALUES(697,'self assisted inverse leg curl','hamstrings');
INSERT INTO exercises VALUES(699,'shoulder tap push-up','pectorals');
INSERT INTO exercises VALUES(705,'side bridge v. 2','abs');
INSERT INTO exercises VALUES(709,'side hip (on parallel bars)','abs');
INSERT INTO exercises VALUES(710,'side hip abduction','abductors');
INSERT INTO exercises VALUES(716,'side push neck stretch','levator scapulae');
INSERT INTO exercises VALUES(717,'side push-up','triceps');
INSERT INTO exercises VALUES(720,'side-to-side chin','lats');
INSERT INTO exercises VALUES(721,'side wrist pull stretch','forearms');
INSERT INTO exercises VALUES(725,'single arm push-up','pectorals');
INSERT INTO exercises VALUES(727,'single leg calf raise (on a dumbbell)','calves');
INSERT INTO exercises VALUES(730,'single leg platform slide','hamstrings');
INSERT INTO exercises VALUES(735,'sit-up v. 2','abs');
INSERT INTO exercises VALUES(738,'sled 45в° calf press','calves');
INSERT INTO exercises VALUES(739,'sled 45в° leg press','glutes');
INSERT INTO exercises VALUES(740,'sled 45в° leg wide press','glutes');
INSERT INTO exercises VALUES(741,'sled closer hack squat','glutes');
INSERT INTO exercises VALUES(742,'sled forward angled calf raise','calves');
INSERT INTO exercises VALUES(743,'sled hack squat','glutes');
INSERT INTO exercises VALUES(744,'sled lying squat','glutes');
INSERT INTO exercises VALUES(746,'smith back shrug','traps');
INSERT INTO exercises VALUES(747,'smith behind neck press','delts');
INSERT INTO exercises VALUES(748,'smith bench press','pectorals');
INSERT INTO exercises VALUES(749,'smith bent knee good morning','glutes');
INSERT INTO exercises VALUES(750,'smith chair squat','quads');
INSERT INTO exercises VALUES(751,'smith close-grip bench press','triceps');
INSERT INTO exercises VALUES(752,'smith deadlift','glutes');
INSERT INTO exercises VALUES(753,'smith decline bench press','pectorals');
INSERT INTO exercises VALUES(754,'smith decline reverse-grip press','pectorals');
INSERT INTO exercises VALUES(755,'smith hack squat','glutes');
INSERT INTO exercises VALUES(756,'smith hip raise','abs');
INSERT INTO exercises VALUES(757,'smith incline bench press','pectorals');
INSERT INTO exercises VALUES(758,'smith incline reverse-grip press','pectorals');
INSERT INTO exercises VALUES(759,'smith incline shoulder raises','serratus anterior');
INSERT INTO exercises VALUES(760,'smith leg press','glutes');
INSERT INTO exercises VALUES(761,'smith narrow row','upper back');
INSERT INTO exercises VALUES(762,'smith rear delt row','delts');
INSERT INTO exercises VALUES(763,'smith reverse calf raises','calves');
INSERT INTO exercises VALUES(764,'smith reverse-grip press','pectorals');
INSERT INTO exercises VALUES(765,'smith seated shoulder press','delts');
INSERT INTO exercises VALUES(766,'smith shoulder press','delts');
INSERT INTO exercises VALUES(767,'smith shrug','traps');
INSERT INTO exercises VALUES(768,'smith single leg split squat','quads');
INSERT INTO exercises VALUES(769,'smith sprint lunge','glutes');
INSERT INTO exercises VALUES(770,'smith squat','glutes');
INSERT INTO exercises VALUES(771,'smith standing back wrist curl','forearms');
INSERT INTO exercises VALUES(772,'smith standing behind head military press','delts');
INSERT INTO exercises VALUES(773,'smith standing leg calf raise','calves');
INSERT INTO exercises VALUES(774,'smith standing military press','delts');
INSERT INTO exercises VALUES(775,'smith upright row','delts');
INSERT INTO exercises VALUES(776,'snatch pull','quads');
INSERT INTO exercises VALUES(777,'spell caster','abs');
INSERT INTO exercises VALUES(778,'spider crawl push up','glutes');
INSERT INTO exercises VALUES(786,'squat jerk','quads');
INSERT INTO exercises VALUES(788,'standing behind neck press','delts');
INSERT INTO exercises VALUES(794,'standing lateral stretch','lats');
INSERT INTO exercises VALUES(795,'standing single leg curl','hamstrings');
INSERT INTO exercises VALUES(796,'standing wheel rollerout','abs');
INSERT INTO exercises VALUES(798,'stationary bike walk','cardiovascular system');
INSERT INTO exercises VALUES(803,'superman push-up','pectorals');
INSERT INTO exercises VALUES(805,'suspended abdominal fallout','abs');
INSERT INTO exercises VALUES(806,'suspended push-up','pectorals');
INSERT INTO exercises VALUES(807,'suspended reverse crunch','abs');
INSERT INTO exercises VALUES(808,'suspended row','upper back');
INSERT INTO exercises VALUES(809,'suspended split squat','quads');
INSERT INTO exercises VALUES(811,'trap bar deadlift','glutes');
INSERT INTO exercises VALUES(812,'triceps dip (bench leg)','triceps');
INSERT INTO exercises VALUES(813,'triceps dip (between benches)','triceps');
INSERT INTO exercises VALUES(814,'triceps dip','triceps');
INSERT INTO exercises VALUES(815,'triceps dips floor','triceps');
INSERT INTO exercises VALUES(816,'triceps press','triceps');
INSERT INTO exercises VALUES(817,'triceps stretch','triceps');
INSERT INTO exercises VALUES(818,'twin handle parallel grip lat pulldown','lats');
INSERT INTO exercises VALUES(826,'vertical leg raise (on parallel bars)','abs');
INSERT INTO exercises VALUES(830,'weighted bench dip','triceps');
INSERT INTO exercises VALUES(832,'weighted crunch','abs');
INSERT INTO exercises VALUES(833,'weighted donkey calf raise','calves');
INSERT INTO exercises VALUES(834,'weighted front raise','delts');
INSERT INTO exercises VALUES(835,'weighted hyperextension (on stability ball)','spine');
INSERT INTO exercises VALUES(840,'weighted overhead crunch (on stability ball)','abs');
INSERT INTO exercises VALUES(841,'weighted pull-up','lats');
INSERT INTO exercises VALUES(844,'weighted round arm','delts');
INSERT INTO exercises VALUES(845,'weighted russian twist (legs up)','abs');
INSERT INTO exercises VALUES(846,'weighted russian twist','abs');
INSERT INTO exercises VALUES(847,'weighted seated bicep curl  (on stability ball)','biceps');
INSERT INTO exercises VALUES(849,'weighted seated twist (on stability ball)','abs');
INSERT INTO exercises VALUES(850,'weighted side bend (on stability ball)','abs');
INSERT INTO exercises VALUES(851,'weighted sissy squat','quads');
INSERT INTO exercises VALUES(852,'weighted squat','glutes');
INSERT INTO exercises VALUES(853,'weighted standing curl','biceps');
INSERT INTO exercises VALUES(854,'weighted standing hand squeeze','forearms');
INSERT INTO exercises VALUES(856,'weighted svend press','pectorals');
INSERT INTO exercises VALUES(857,'wheel rollerout','abs');
INSERT INTO exercises VALUES(858,'wind sprints','abs');
INSERT INTO exercises VALUES(859,'wrist rollerer','forearms');
INSERT INTO exercises VALUES(860,'cable kickback','triceps');
INSERT INTO exercises VALUES(861,'cable seated row','upper back');
INSERT INTO exercises VALUES(862,'cable twist (up-down)','abs');
INSERT INTO exercises VALUES(863,'dumbbell lying external shoulder rotation','delts');
INSERT INTO exercises VALUES(864,'dumbbell upright shoulder external rotation','delts');
INSERT INTO exercises VALUES(865,'lying leg-hip raise','abs');
INSERT INTO exercises VALUES(866,'weighted hanging leg-hip raise','abs');
INSERT INTO exercises VALUES(868,'cable curl','biceps');
INSERT INTO exercises VALUES(869,'lever shoulder press  v. 2','delts');
INSERT INTO exercises VALUES(870,'butt-ups','abs');
INSERT INTO exercises VALUES(871,'tuck crunch','abs');
INSERT INTO exercises VALUES(872,'reverse crunch','abs');
INSERT INTO exercises VALUES(873,'cable reverse crunch','abs');
INSERT INTO exercises VALUES(874,'cable standing crunch (with rope attachment)','abs');
INSERT INTO exercises VALUES(968,'band alternating biceps curl','biceps');
INSERT INTO exercises VALUES(969,'band alternating v-up','abs');
INSERT INTO exercises VALUES(970,'band assisted pull-up','lats');
INSERT INTO exercises VALUES(971,'band assisted wheel rollerout','abs');
INSERT INTO exercises VALUES(972,'band bicycle crunch','abs');
INSERT INTO exercises VALUES(974,'band close-grip pulldown','lats');
INSERT INTO exercises VALUES(975,'band close-grip push-up','triceps');
INSERT INTO exercises VALUES(976,'band concentration curl','biceps');
INSERT INTO exercises VALUES(977,'band front lateral raise','delts');
INSERT INTO exercises VALUES(978,'band front raise','delts');
INSERT INTO exercises VALUES(979,'band horizontal pallof press','abs');
INSERT INTO exercises VALUES(980,'band bent-over hip extension','glutes');
INSERT INTO exercises VALUES(981,'band jack knife sit-up','abs');
INSERT INTO exercises VALUES(983,'band kneeling one arm pulldown','lats');
INSERT INTO exercises VALUES(984,'band lying hip internal rotation','glutes');
INSERT INTO exercises VALUES(985,'band kneeling twisting crunch','abs');
INSERT INTO exercises VALUES(986,'band one arm overhead biceps curl','biceps');
INSERT INTO exercises VALUES(987,'band one arm single leg split squat','quads');
INSERT INTO exercises VALUES(988,'band one arm standing low row','upper back');
INSERT INTO exercises VALUES(989,'band one arm twisting chest press','pectorals');
INSERT INTO exercises VALUES(990,'band one arm twisting seated row','upper back');
INSERT INTO exercises VALUES(991,'band pull through','glutes');
INSERT INTO exercises VALUES(992,'band push sit-up','abs');
INSERT INTO exercises VALUES(993,'band reverse fly','delts');
INSERT INTO exercises VALUES(994,'band reverse wrist curl','forearms');
INSERT INTO exercises VALUES(996,'band seated hip internal rotation','glutes');
INSERT INTO exercises VALUES(997,'band shoulder press','delts');
INSERT INTO exercises VALUES(998,'band side triceps extension','triceps');
INSERT INTO exercises VALUES(999,'band single leg calf raise','calves');
INSERT INTO exercises VALUES(1000,'band single leg reverse calf raise','calves');
INSERT INTO exercises VALUES(1001,'band single leg split squat','quads');
INSERT INTO exercises VALUES(1002,'band lying straight leg raise','abs');
INSERT INTO exercises VALUES(1003,'band squat row','glutes');
INSERT INTO exercises VALUES(1004,'band squat','glutes');
INSERT INTO exercises VALUES(1005,'band standing crunch','abs');
INSERT INTO exercises VALUES(1007,'band standing twisting crunch','abs');
INSERT INTO exercises VALUES(1008,'band step-up','glutes');
INSERT INTO exercises VALUES(1009,'band stiff leg deadlift','glutes');
INSERT INTO exercises VALUES(1010,'band straight leg deadlift','spine');
INSERT INTO exercises VALUES(1011,'band seated twist','abs');
INSERT INTO exercises VALUES(1012,'band twisting overhead press','delts');
INSERT INTO exercises VALUES(1013,'band underhand pulldown','lats');
INSERT INTO exercises VALUES(1014,'band v-up','abs');
INSERT INTO exercises VALUES(1015,'band vertical pallof press','abs');
INSERT INTO exercises VALUES(1016,'band wrist curl','forearms');
INSERT INTO exercises VALUES(1017,'band y-raise','delts');
INSERT INTO exercises VALUES(1018,'band shrug','traps');
INSERT INTO exercises VALUES(1022,'band standing rear delt row','delts');
INSERT INTO exercises VALUES(1023,'band straight back stiff leg deadlift','glutes');
INSERT INTO exercises VALUES(1160,'burpee','cardiovascular system');
INSERT INTO exercises VALUES(1167,'dynamic chest stretch (male)','pectorals');
INSERT INTO exercises VALUES(1201,'dumbbell burpee','cardiovascular system');
INSERT INTO exercises VALUES(1253,'lever donkey calf raise','calves');
INSERT INTO exercises VALUES(1254,'band bench press','pectorals');
INSERT INTO exercises VALUES(1255,'barbell decline pullover','pectorals');
INSERT INTO exercises VALUES(1256,'barbell reverse grip decline bench press','pectorals');
INSERT INTO exercises VALUES(1257,'barbell reverse grip incline bench press','pectorals');
INSERT INTO exercises VALUES(1258,'barbell wide reverse grip bench press','pectorals');
INSERT INTO exercises VALUES(1259,'behind head chest stretch','pectorals');
INSERT INTO exercises VALUES(1260,'cable decline one arm press','pectorals');
INSERT INTO exercises VALUES(1261,'cable decline press','pectorals');
INSERT INTO exercises VALUES(1262,'cable one arm decline chest fly','pectorals');
INSERT INTO exercises VALUES(1263,'cable one arm fly on exercise ball','pectorals');
INSERT INTO exercises VALUES(1264,'cable one arm incline fly on exercise ball','pectorals');
INSERT INTO exercises VALUES(1265,'cable one arm incline press','pectorals');
INSERT INTO exercises VALUES(1266,'cable one arm incline press on exercise ball','pectorals');
INSERT INTO exercises VALUES(1267,'cable one arm press on exercise ball','pectorals');
INSERT INTO exercises VALUES(1268,'cable press on exercise ball','pectorals');
INSERT INTO exercises VALUES(1269,'cable standing up straight crossovers','pectorals');
INSERT INTO exercises VALUES(1270,'cable upper chest crossovers','pectorals');
INSERT INTO exercises VALUES(1271,'chest and front of shoulder stretch','pectorals');
INSERT INTO exercises VALUES(1272,'chest stretch with exercise ball','pectorals');
INSERT INTO exercises VALUES(1273,'clap push up','pectorals');
INSERT INTO exercises VALUES(1274,'deep push up','pectorals');
INSERT INTO exercises VALUES(1275,'drop push up','pectorals');
INSERT INTO exercises VALUES(1276,'dumbbell decline one arm fly','pectorals');
INSERT INTO exercises VALUES(1277,'dumbbell fly on exercise ball','pectorals');
INSERT INTO exercises VALUES(1278,'dumbbell incline fly on exercise ball','pectorals');
INSERT INTO exercises VALUES(1279,'dumbbell incline one arm fly','pectorals');
INSERT INTO exercises VALUES(1280,'dumbbell incline one arm fly on exercise ball','pectorals');
INSERT INTO exercises VALUES(1281,'dumbbell incline one arm press','pectorals');
INSERT INTO exercises VALUES(1282,'dumbbell incline one arm press on exercise ball','pectorals');
INSERT INTO exercises VALUES(1283,'dumbbell incline press on exercise ball','pectorals');
INSERT INTO exercises VALUES(1284,'dumbbell lying pullover on exercise ball','pectorals');
INSERT INTO exercises VALUES(1285,'dumbbell one arm bench fly','pectorals');
INSERT INTO exercises VALUES(1286,'dumbbell one arm chest fly on exercise ball','pectorals');
INSERT INTO exercises VALUES(1287,'dumbbell one arm decline chest press','pectorals');
INSERT INTO exercises VALUES(1288,'dumbbell one arm fly on exercise ball','pectorals');
INSERT INTO exercises VALUES(1289,'dumbbell one arm incline chest press','pectorals');
INSERT INTO exercises VALUES(1290,'dumbbell one arm press on exercise ball','pectorals');
INSERT INTO exercises VALUES(1291,'dumbbell one arm pullover on exercise ball','pectorals');
INSERT INTO exercises VALUES(1292,'dumbbell one leg fly on exercise ball','pectorals');
INSERT INTO exercises VALUES(1293,'dumbbell press on exercise ball','pectorals');
INSERT INTO exercises VALUES(1294,'dumbbell pullover hip extension on exercise ball','pectorals');
INSERT INTO exercises VALUES(1295,'dumbbell pullover on exercise ball','pectorals');
INSERT INTO exercises VALUES(1296,'exercise ball pike push up','pectorals');
INSERT INTO exercises VALUES(1297,'isometric chest squeeze','pectorals');
INSERT INTO exercises VALUES(1298,'kettlebell one arm floor press','pectorals');
INSERT INTO exercises VALUES(1299,'lever incline chest press','pectorals');
INSERT INTO exercises VALUES(1300,'lever decline chest press','pectorals');
INSERT INTO exercises VALUES(1301,'machine inner chest press','pectorals');
INSERT INTO exercises VALUES(1302,'medicine ball chest pass','pectorals');
INSERT INTO exercises VALUES(1303,'medicine ball chest push from 3 point stance','pectorals');
INSERT INTO exercises VALUES(1304,'medicine ball chest push multiple response','pectorals');
INSERT INTO exercises VALUES(1305,'medicine ball chest push single response','pectorals');
INSERT INTO exercises VALUES(1306,'plyo push up','pectorals');
INSERT INTO exercises VALUES(1307,'push up on bosu ball','pectorals');
INSERT INTO exercises VALUES(1308,'smith wide grip bench press','pectorals');
INSERT INTO exercises VALUES(1309,'smith wide grip decline bench press','pectorals');
INSERT INTO exercises VALUES(1310,'weighted drop push up','pectorals');
INSERT INTO exercises VALUES(1311,'wide hand push up','pectorals');
INSERT INTO exercises VALUES(1312,'medicine ball chest push with run release','pectorals');
INSERT INTO exercises VALUES(1313,'lever unilateral row','upper back');
INSERT INTO exercises VALUES(1314,'back extension on exercise ball','spine');
INSERT INTO exercises VALUES(1316,'barbell bent arm pullover','lats');
INSERT INTO exercises VALUES(1317,'barbell reverse grip incline bench row','upper back');
INSERT INTO exercises VALUES(1318,'cable incline bench row','upper back');
INSERT INTO exercises VALUES(1319,'cable palm rotational row','upper back');
INSERT INTO exercises VALUES(1320,'cable rope crossover seated row','upper back');
INSERT INTO exercises VALUES(1321,'cable rope elevated seated row','upper back');
INSERT INTO exercises VALUES(1322,'cable rope extension incline bench row','upper back');
INSERT INTO exercises VALUES(1323,'cable rope seated row','upper back');
INSERT INTO exercises VALUES(1324,'cable upper row','upper back');
INSERT INTO exercises VALUES(1325,'cable wide grip rear pulldown behind neck','lats');
INSERT INTO exercises VALUES(1326,'chin-up','lats');
INSERT INTO exercises VALUES(1327,'close grip chin-up','lats');
INSERT INTO exercises VALUES(1328,'dumbbell lying rear delt row','upper back');
INSERT INTO exercises VALUES(1329,'dumbbell palm rotational bent over row','upper back');
INSERT INTO exercises VALUES(1330,'dumbbell reverse grip incline bench one arm row','upper back');
INSERT INTO exercises VALUES(1331,'dumbbell reverse grip incline bench two arm row','upper back');
INSERT INTO exercises VALUES(1332,'exercise ball alternating arm ups','lats');
INSERT INTO exercises VALUES(1333,'exercise ball back extension with arms extended','spine');
INSERT INTO exercises VALUES(1334,'exercise ball back extension with hands behind head','spine');
INSERT INTO exercises VALUES(1335,'exercise ball back extension with knees off ground','spine');
INSERT INTO exercises VALUES(1336,'exercise ball back extension with rotation','spine');
INSERT INTO exercises VALUES(1338,'exercise ball hug','spine');
INSERT INTO exercises VALUES(1339,'exercise ball lat stretch','lats');
INSERT INTO exercises VALUES(1341,'exercise ball lower back stretch (pyramid)','lats');
INSERT INTO exercises VALUES(1342,'exercise ball lying side lat stretch','lats');
INSERT INTO exercises VALUES(1343,'exercise ball prone leg raise','spine');
INSERT INTO exercises VALUES(1344,'ez bar reverse grip bent over row','upper back');
INSERT INTO exercises VALUES(1345,'kettlebell two arm row','upper back');
INSERT INTO exercises VALUES(1346,'kneeling lat stretch','lats');
INSERT INTO exercises VALUES(1347,'lever one arm lateral wide pulldown ','lats');
INSERT INTO exercises VALUES(1348,'lever reverse grip vertical row','upper back');
INSERT INTO exercises VALUES(1349,'lever reverse t-bar row','upper back');
INSERT INTO exercises VALUES(1350,'lever seated row','upper back');
INSERT INTO exercises VALUES(1351,'lever t-bar reverse grip row','upper back');
INSERT INTO exercises VALUES(1352,'lower back curl','spine');
INSERT INTO exercises VALUES(1353,'medicine ball catch and overhead throw','lats');
INSERT INTO exercises VALUES(1354,'medicine ball overhead slam','upper back');
INSERT INTO exercises VALUES(1355,'one arm against wall','lats');
INSERT INTO exercises VALUES(1356,'lever one arm lateral high row','upper back');
INSERT INTO exercises VALUES(1358,'side lying floor stretch','lats');
INSERT INTO exercises VALUES(1359,'smith bent over row','upper back');
INSERT INTO exercises VALUES(1360,'smith one arm row','upper back');
INSERT INTO exercises VALUES(1361,'smith reverse grip bent over row','upper back');
INSERT INTO exercises VALUES(1362,'sphinx','spine');
INSERT INTO exercises VALUES(1363,'spine stretch','spine');
INSERT INTO exercises VALUES(1364,'standing pelvic tilt','spine');
INSERT INTO exercises VALUES(1365,'upper back stretch','upper back');
INSERT INTO exercises VALUES(1366,'upward facing dog','spine');
INSERT INTO exercises VALUES(1367,'wide grip rear pull-up','lats');
INSERT INTO exercises VALUES(1368,'ankle circles','calves');
INSERT INTO exercises VALUES(1369,'band two legs calf raise - (band under both legs) v. 2','calves');
INSERT INTO exercises VALUES(1370,'barbell floor calf raise','calves');
INSERT INTO exercises VALUES(1371,'barbell seated calf raise','calves');
INSERT INTO exercises VALUES(1372,'barbell standing calf raise','calves');
INSERT INTO exercises VALUES(1373,'bodyweight standing calf raise','calves');
INSERT INTO exercises VALUES(1374,'box jump down with one leg stabilization','calves');
INSERT INTO exercises VALUES(1375,'cable standing calf raise','calves');
INSERT INTO exercises VALUES(1376,'cable standing one leg calf raise','calves');
INSERT INTO exercises VALUES(1377,'calf stretch with hands against wall','calves');
INSERT INTO exercises VALUES(1378,'calf stretch with rope','calves');
INSERT INTO exercises VALUES(1379,'dumbbell seated calf raise','calves');
INSERT INTO exercises VALUES(1380,'dumbbell seated one leg calf raise - hammer grip','calves');
INSERT INTO exercises VALUES(1381,'dumbbell seated one leg calf raise - palm up','calves');
INSERT INTO exercises VALUES(1382,'exercise ball on the wall calf raise','calves');
INSERT INTO exercises VALUES(1383,'hack calf raise','calves');
INSERT INTO exercises VALUES(1384,'hack one leg calf raise','calves');
INSERT INTO exercises VALUES(1385,'lever seated squat calf raise on leg press machine','calves');
INSERT INTO exercises VALUES(1386,'one leg donkey calf raise','calves');
INSERT INTO exercises VALUES(1387,'one leg floor calf raise','calves');
INSERT INTO exercises VALUES(1388,'peroneals stretch','calves');
INSERT INTO exercises VALUES(1389,'posterior tibialis stretch','calves');
INSERT INTO exercises VALUES(1390,'seated calf stretch (male)','calves');
INSERT INTO exercises VALUES(1391,'sled calf press on leg press','calves');
INSERT INTO exercises VALUES(1392,'sled one leg calf press on leg press','calves');
INSERT INTO exercises VALUES(1393,'smith one leg floor calf raise','calves');
INSERT INTO exercises VALUES(1394,'smith reverse calf raises','calves');
INSERT INTO exercises VALUES(1395,'smith seated one leg calf raise','calves');
INSERT INTO exercises VALUES(1396,'smith toe raise','calves');
INSERT INTO exercises VALUES(1397,'standing calves','calves');
INSERT INTO exercises VALUES(1398,'standing calves calf stretch','calves');
INSERT INTO exercises VALUES(1399,'bench dip on floor','triceps');
INSERT INTO exercises VALUES(1401,'muscle-up (on vertical bar)','lats');
INSERT INTO exercises VALUES(1403,'neck side stretch','levator scapulae');
INSERT INTO exercises VALUES(1405,'back pec stretch','lats');
INSERT INTO exercises VALUES(1407,'calf push stretch with hands against wall','calves');
INSERT INTO exercises VALUES(1408,'band hip lift','glutes');
INSERT INTO exercises VALUES(1409,'barbell glute bridge','glutes');
INSERT INTO exercises VALUES(1410,'barbell lateral lunge','glutes');
INSERT INTO exercises VALUES(1411,'barbell palms down wrist curl over a bench','forearms');
INSERT INTO exercises VALUES(1412,'barbell palms up wrist curl over a bench','forearms');
INSERT INTO exercises VALUES(1413,'cable reverse one arm curl','biceps');
INSERT INTO exercises VALUES(1414,'dumbbell one arm reverse preacher curl','biceps');
INSERT INTO exercises VALUES(1415,'dumbbell one arm seated neutral wrist curl','forearms');
INSERT INTO exercises VALUES(1416,'exercise ball one leg prone lower body rotation','glutes');
INSERT INTO exercises VALUES(1417,'exercise ball one legged diagonal kick hamstring curl','glutes');
INSERT INTO exercises VALUES(1418,'hug keens to chest','glutes');
INSERT INTO exercises VALUES(1419,'iron cross stretch','glutes');
INSERT INTO exercises VALUES(1420,'kneeling jump squat','glutes');
INSERT INTO exercises VALUES(1421,'modified push up to lower arms','forearms');
INSERT INTO exercises VALUES(1422,'pelvic tilt into bridge','glutes');
INSERT INTO exercises VALUES(1423,'reverse hyper on flat bench','glutes');
INSERT INTO exercises VALUES(1424,'seated glute stretch','glutes');
INSERT INTO exercises VALUES(1425,'sled 45 degrees one leg press','glutes');
INSERT INTO exercises VALUES(1426,'smith seated wrist curl','forearms');
INSERT INTO exercises VALUES(1427,'straight leg outer hip abductor','abductors');
INSERT INTO exercises VALUES(1428,'wrist circles','forearms');
INSERT INTO exercises VALUES(1429,'wide grip pull-up','lats');
INSERT INTO exercises VALUES(1430,'chest dip (on dip-pull-up cage)','pectorals');
INSERT INTO exercises VALUES(1431,'assisted standing chin-up','lats');
INSERT INTO exercises VALUES(1432,'assisted standing pull-up','lats');
INSERT INTO exercises VALUES(1433,'smith front squat (clean grip)','glutes');
INSERT INTO exercises VALUES(1434,'smith low bar squat','glutes');
INSERT INTO exercises VALUES(1435,'barbell low bar squat','glutes');
INSERT INTO exercises VALUES(1436,'barbell high bar squat','glutes');
INSERT INTO exercises VALUES(1437,'dumbbell finger curls','forearms');
INSERT INTO exercises VALUES(1438,'kettlebell seated two arm military press','delts');
INSERT INTO exercises VALUES(1439,'lever gripless shrug v. 2','traps');
INSERT INTO exercises VALUES(1441,'dumbbell over bench one arm reverse wrist curl','forearms');
INSERT INTO exercises VALUES(1451,'lever seated dip','triceps');
INSERT INTO exercises VALUES(1452,'lever seated crunch','abs');
INSERT INTO exercises VALUES(1456,'barbell standing close grip military press','delts');
INSERT INTO exercises VALUES(1457,'barbell standing wide military press','delts');
INSERT INTO exercises VALUES(1458,'ez barbell seated curls','biceps');
INSERT INTO exercises VALUES(1459,'dumbbell romanian deadlift','glutes');
INSERT INTO exercises VALUES(1460,'walking lunge','glutes');
INSERT INTO exercises VALUES(1461,'barbell full squat (back pov)','glutes');
INSERT INTO exercises VALUES(1462,'barbell full squat (side pov)','glutes');
INSERT INTO exercises VALUES(1463,'sled 45в° leg press (side pov)','glutes');
INSERT INTO exercises VALUES(1464,'sled 45в° leg press (back pov)','glutes');
INSERT INTO exercises VALUES(1466,'twist hip lift','glutes');
INSERT INTO exercises VALUES(1467,'push-up on lower arms','triceps');
INSERT INTO exercises VALUES(1468,'crab twist toe touch','abs');
INSERT INTO exercises VALUES(1471,'inchworm','abs');
INSERT INTO exercises VALUES(1472,'forward jump','quads');
INSERT INTO exercises VALUES(1473,'backward jump','quads');
INSERT INTO exercises VALUES(1476,'one leg squat','glutes');
INSERT INTO exercises VALUES(1479,'lever incline chest press v. 2','pectorals');
INSERT INTO exercises VALUES(1489,'sissy squat','quads');
INSERT INTO exercises VALUES(1490,'standing calf raise (on a staircase)','calves');
INSERT INTO exercises VALUES(1494,'butterfly yoga pose','adductors');
INSERT INTO exercises VALUES(1495,'oblique crunch v. 2','abs');
INSERT INTO exercises VALUES(1496,'sledge hammer','abs');
INSERT INTO exercises VALUES(1511,'hamstring stretch','hamstrings');
INSERT INTO exercises VALUES(1512,'all fours squad stretch','quads');
INSERT INTO exercises VALUES(1545,'barbell full zercher squat','glutes');
INSERT INTO exercises VALUES(1548,'chair leg extended stretch','quads');
INSERT INTO exercises VALUES(1559,'exercise ball hip flexor stretch','glutes');
INSERT INTO exercises VALUES(1560,'exercise ball seated hamstring stretch','hamstrings');
INSERT INTO exercises VALUES(1564,'intermediate hip flexor and quad stretch','quads');
INSERT INTO exercises VALUES(1576,'leg up hamstring stretch','hamstrings');
INSERT INTO exercises VALUES(1582,'reclining big toe pose with rope','hamstrings');
INSERT INTO exercises VALUES(1585,'runners stretch','hamstrings');
INSERT INTO exercises VALUES(1587,'seated wide angle pose sequence','hamstrings');
INSERT INTO exercises VALUES(1599,'standing hamstring and calf stretch with strap','hamstrings');
INSERT INTO exercises VALUES(1604,'world greatest stretch','hamstrings');
INSERT INTO exercises VALUES(1614,'lever preacher curl v. 2','biceps');
INSERT INTO exercises VALUES(1615,'lever hammer grip preacher curl','biceps');
INSERT INTO exercises VALUES(1616,'lever reverse grip preacher curl','biceps');
INSERT INTO exercises VALUES(1617,'dumbbell decline one arm hammer press','triceps');
INSERT INTO exercises VALUES(1618,'dumbbell incline hammer press on exercise ball','triceps');
INSERT INTO exercises VALUES(1619,'dumbbell incline one arm hammer press','triceps');
INSERT INTO exercises VALUES(1620,'dumbbell incline one arm hammer press on exercise ball','triceps');
INSERT INTO exercises VALUES(1621,'dumbbell one arm hammer press on exercise ball','triceps');
INSERT INTO exercises VALUES(1622,'dumbbell one arm reverse grip press','pectorals');
INSERT INTO exercises VALUES(1623,'dumbbell palms in incline bench press','triceps');
INSERT INTO exercises VALUES(1624,'dumbbell reverse bench press','pectorals');
INSERT INTO exercises VALUES(1625,'smith machine decline close grip bench press','triceps');
INSERT INTO exercises VALUES(1626,'smith machine reverse decline close grip bench press','pectorals');
INSERT INTO exercises VALUES(1627,'ez barbell close grip preacher curl','biceps');
INSERT INTO exercises VALUES(1628,'ez barbell spider curl','biceps');
INSERT INTO exercises VALUES(1629,'barbell standing wide grip biceps curl','biceps');
INSERT INTO exercises VALUES(1630,'cable close grip curl','biceps');
INSERT INTO exercises VALUES(1631,'cable concentration curl','biceps');
INSERT INTO exercises VALUES(1632,'cable drag curl','biceps');
INSERT INTO exercises VALUES(1633,'cable one arm preacher curl','biceps');
INSERT INTO exercises VALUES(1634,'cable lying bicep curl','biceps');
INSERT INTO exercises VALUES(1635,'cable one arm reverse preacher curl','biceps');
INSERT INTO exercises VALUES(1636,'cable overhead curl','biceps');
INSERT INTO exercises VALUES(1637,'cable overhead curl on exercise ball','biceps');
INSERT INTO exercises VALUES(1638,'cable pulldown bicep curl','biceps');
INSERT INTO exercises VALUES(1639,'cable rope hammer preacher curl','biceps');
INSERT INTO exercises VALUES(1640,'cable rope one arm hammer preacher curl','biceps');
INSERT INTO exercises VALUES(1641,'cable seated curl','biceps');
INSERT INTO exercises VALUES(1642,'cable seated one arm concentration curl','biceps');
INSERT INTO exercises VALUES(1643,'cable seated overhead curl','biceps');
INSERT INTO exercises VALUES(1644,'cable squatting curl','biceps');
INSERT INTO exercises VALUES(1645,'cable two arm curl on incline bench','biceps');
INSERT INTO exercises VALUES(1646,'dumbbell alternate hammer preacher curl','biceps');
INSERT INTO exercises VALUES(1647,'dumbbell alternate preacher curl','biceps');
INSERT INTO exercises VALUES(1648,'dumbbell alternate seated hammer curl','biceps');
INSERT INTO exercises VALUES(1649,'dumbbell alternating bicep curl with leg raised on exercise ball','biceps');
INSERT INTO exercises VALUES(1650,'dumbbell alternating seated bicep curl on exercise ball','biceps');
INSERT INTO exercises VALUES(1651,'dumbbell bicep curl lunge with bowling motion','biceps');
INSERT INTO exercises VALUES(1652,'dumbbell bicep curl on exercise ball with leg raised','biceps');
INSERT INTO exercises VALUES(1653,'dumbbell bicep curl with stork stance','biceps');
INSERT INTO exercises VALUES(1654,'dumbbell biceps curl reverse','biceps');
INSERT INTO exercises VALUES(1655,'dumbbell biceps curl squat','biceps');
INSERT INTO exercises VALUES(1656,'dumbbell biceps curl v sit on bosu ball','biceps');
INSERT INTO exercises VALUES(1657,'dumbbell cross body hammer curl v. 2','biceps');
INSERT INTO exercises VALUES(1658,'dumbbell lunge with bicep curl','biceps');
INSERT INTO exercises VALUES(1659,'dumbbell hammer curl on exercise ball','biceps');
INSERT INTO exercises VALUES(1660,'dumbbell kneeling bicep curl exercise ball','biceps');
INSERT INTO exercises VALUES(1661,'dumbbell lying supine biceps curl','biceps');
INSERT INTO exercises VALUES(1662,'dumbbell lying wide curl','biceps');
INSERT INTO exercises VALUES(1663,'dumbbell one arm hammer preacher curl','biceps');
INSERT INTO exercises VALUES(1664,'dumbbell high curl','biceps');
INSERT INTO exercises VALUES(1665,'dumbbell one arm prone curl','biceps');
INSERT INTO exercises VALUES(1666,'dumbbell one arm prone hammer curl','biceps');
INSERT INTO exercises VALUES(1667,'dumbbell one arm reverse spider curl','biceps');
INSERT INTO exercises VALUES(1668,'dumbbell one arm seated bicep curl on exercise ball','biceps');
INSERT INTO exercises VALUES(1669,'dumbbell one arm seated hammer curl','biceps');
INSERT INTO exercises VALUES(1670,'dumbbell one arm standing curl','biceps');
INSERT INTO exercises VALUES(1671,'dumbbell one arm standing hammer curl','biceps');
INSERT INTO exercises VALUES(1672,'dumbbell one arm zottman preacher curl','biceps');
INSERT INTO exercises VALUES(1673,'dumbbell preacher curl over exercise ball','biceps');
INSERT INTO exercises VALUES(1674,'dumbbell prone incline hammer curl','biceps');
INSERT INTO exercises VALUES(1675,'dumbbell reverse spider curl','biceps');
INSERT INTO exercises VALUES(1676,'dumbbell seated alternate hammer curl on exercise ball','biceps');
INSERT INTO exercises VALUES(1677,'dumbbell seated bicep curl','biceps');
INSERT INTO exercises VALUES(1678,'dumbbell seated hammer curl','biceps');
INSERT INTO exercises VALUES(1679,'dumbbell seated one arm bicep curl on exercise ball with leg raised','biceps');
INSERT INTO exercises VALUES(1680,'dumbbell standing one arm curl over incline bench','biceps');
INSERT INTO exercises VALUES(1682,'ez bar seated close grip concentration curl','biceps');
INSERT INTO exercises VALUES(1683,'smith machine bicep curl','biceps');
INSERT INTO exercises VALUES(1684,'dumbbell step up single leg balance with bicep curl','biceps');
INSERT INTO exercises VALUES(1685,'squat to overhead reach','quads');
INSERT INTO exercises VALUES(1686,'squat to overhead reach with twist','quads');
INSERT INTO exercises VALUES(1687,'posterior step to overhead reach','abs');
INSERT INTO exercises VALUES(1688,'lunge with twist','abs');
INSERT INTO exercises VALUES(1689,'push and pull bodyweight','pectorals');
INSERT INTO exercises VALUES(1700,'dumbbell push press','delts');
INSERT INTO exercises VALUES(1701,'medicine ball close grip push up','triceps');
INSERT INTO exercises VALUES(1705,'squat on bosu ball','quads');
INSERT INTO exercises VALUES(1707,'prone twist on stability ball','abs');
INSERT INTO exercises VALUES(1708,'assisted lying calves stretch','calves');
INSERT INTO exercises VALUES(1709,'assisted lying glutes stretch','glutes');
INSERT INTO exercises VALUES(1710,'assisted lying gluteus and piriformis stretch','glutes');
INSERT INTO exercises VALUES(1712,'assisted side lying adductor stretch','adductors');
INSERT INTO exercises VALUES(1713,'assisted prone lying quads stretch','quads');
INSERT INTO exercises VALUES(1714,'assisted prone rectus femoris stretch','abs');
INSERT INTO exercises VALUES(1716,'assisted seated pectoralis major stretch with stability ball','pectorals');
INSERT INTO exercises VALUES(1717,'cable squat row (with rope attachment)','lats');
INSERT INTO exercises VALUES(1718,'barbell seated close grip behind neck triceps extension','triceps');
INSERT INTO exercises VALUES(1719,'barbell incline close grip bench press','triceps');
INSERT INTO exercises VALUES(1720,'barbell lying back of the head tricep extension','triceps');
INSERT INTO exercises VALUES(1721,'barbell reverse grip skullcrusher','triceps');
INSERT INTO exercises VALUES(1722,'cable high pulley overhead tricep extension','triceps');
INSERT INTO exercises VALUES(1723,'cable one arm tricep pushdown','triceps');
INSERT INTO exercises VALUES(1724,'cable rope high pulley overhead tricep extension','triceps');
INSERT INTO exercises VALUES(1725,'cable rope incline tricep extension','triceps');
INSERT INTO exercises VALUES(1726,'cable rope lying on floor tricep extension','triceps');
INSERT INTO exercises VALUES(1727,'cable standing reverse grip one arm overhead tricep extension','triceps');
INSERT INTO exercises VALUES(1728,'cable two arm tricep kickback','triceps');
INSERT INTO exercises VALUES(1729,'dumbbell lying alternate extension','triceps');
INSERT INTO exercises VALUES(1730,'dumbbell seated bent over alternate kickback','triceps');
INSERT INTO exercises VALUES(1731,'dumbbell close grip press','triceps');
INSERT INTO exercises VALUES(1732,'dumbbell forward lunge triceps extension','triceps');
INSERT INTO exercises VALUES(1733,'dumbbell incline two arm extension','triceps');
INSERT INTO exercises VALUES(1734,'dumbbell kickbacks on exercise ball','triceps');
INSERT INTO exercises VALUES(1735,'dumbbell lying single extension','triceps');
INSERT INTO exercises VALUES(1736,'dumbbell one arm french press on exercise ball','triceps');
INSERT INTO exercises VALUES(1737,'dumbbell seated bent over triceps extension','triceps');
INSERT INTO exercises VALUES(1738,'dumbbell seated reverse grip one arm overhead tricep extension','triceps');
INSERT INTO exercises VALUES(1739,'dumbbell standing alternating tricep kickback','triceps');
INSERT INTO exercises VALUES(1740,'dumbbell standing bent over one arm triceps extension','triceps');
INSERT INTO exercises VALUES(1741,'dumbbell standing bent over two arm triceps extension','triceps');
INSERT INTO exercises VALUES(1742,'dumbbell tricep kickback with stork stance','triceps');
INSERT INTO exercises VALUES(1743,'dumbbell twisting bench press','triceps');
INSERT INTO exercises VALUES(1744,'exercise ball dip','triceps');
INSERT INTO exercises VALUES(1745,'exercise ball seated triceps stretch','triceps');
INSERT INTO exercises VALUES(1746,'exercise ball supine triceps extension','triceps');
INSERT INTO exercises VALUES(1747,'ez bar french press on exercise ball','triceps');
INSERT INTO exercises VALUES(1748,'ez bar lying close grip triceps extension behind head','triceps');
INSERT INTO exercises VALUES(1749,'ez bar standing french press','triceps');
INSERT INTO exercises VALUES(1750,'medicine ball supine chest throw','triceps');
INSERT INTO exercises VALUES(1751,'barbell pin presses','triceps');
INSERT INTO exercises VALUES(1752,'smith machine incline tricep extension','triceps');
INSERT INTO exercises VALUES(1753,'three bench dip','triceps');
INSERT INTO exercises VALUES(1754,'weighted three bench dips','triceps');
INSERT INTO exercises VALUES(1755,'weighted tricep dips','triceps');
INSERT INTO exercises VALUES(1756,'barbell single leg deadlift','glutes');
INSERT INTO exercises VALUES(1757,'dumbbell single leg deadlift','glutes');
INSERT INTO exercises VALUES(1758,'assisted sit-up','abs');
INSERT INTO exercises VALUES(1759,'single leg squat (pistol) male','glutes');
INSERT INTO exercises VALUES(1760,'dumbbell goblet squat','quads');
INSERT INTO exercises VALUES(1761,'hanging oblique knee raise','abs');
INSERT INTO exercises VALUES(1763,'shoulder grip pull-up','lats');
INSERT INTO exercises VALUES(1764,'hanging leg hip raise','abs');
INSERT INTO exercises VALUES(1765,'dumbbell upright row (back pov)','delts');
INSERT INTO exercises VALUES(1766,'self assisted inverse leg curl','hamstrings');
INSERT INTO exercises VALUES(1767,'weighted triceps dip on high parallel bars','triceps');
INSERT INTO exercises VALUES(1769,'bodyweight side lying biceps curl','biceps');
INSERT INTO exercises VALUES(1770,'biceps leg concentration curl','biceps');
INSERT INTO exercises VALUES(1771,'bodyweight kneeling triceps extension','triceps');
INSERT INTO exercises VALUES(1772,'elbow lift - reverse push-up','upper back');
INSERT INTO exercises VALUES(1773,'one arm towel row','upper back');
INSERT INTO exercises VALUES(1774,'side bridge hip abduction','abductors');
INSERT INTO exercises VALUES(1775,'side plank hip adduction','adductors');
INSERT INTO exercises VALUES(2133,'farmers walk','quads');
INSERT INTO exercises VALUES(2135,'weighted front plank','abs');
INSERT INTO exercises VALUES(2136,'dumbbell cuban press v. 2','delts');
INSERT INTO exercises VALUES(2137,'dumbbell arnold press','delts');
INSERT INTO exercises VALUES(2138,'stationary bike run v. 3','cardiovascular system');
INSERT INTO exercises VALUES(2139,'hands bike','pectorals');
INSERT INTO exercises VALUES(2141,'walk elliptical cross trainer','cardiovascular system');
INSERT INTO exercises VALUES(2142,'ski ergometer','triceps');
INSERT INTO exercises VALUES(2143,'dumbbell standing around world','delts');
INSERT INTO exercises VALUES(2144,'cable seated chest press','pectorals');
INSERT INTO exercises VALUES(2186,'ez barbell decline triceps extension','triceps');
INSERT INTO exercises VALUES(2187,'barbell reverse close-grip bench press','triceps');
INSERT INTO exercises VALUES(2188,'dumbbell seated triceps extension','triceps');
INSERT INTO exercises VALUES(2189,'dumbbells seated triceps extension','triceps');
INSERT INTO exercises VALUES(2202,'roller hip stretch','glutes');
INSERT INTO exercises VALUES(2203,'roller seated shoulder flexor depresor retractor','pectorals');
INSERT INTO exercises VALUES(2204,'roller body saw','abs');
INSERT INTO exercises VALUES(2205,'roller hip lat stretch','glutes');
INSERT INTO exercises VALUES(2206,'roller reverse crunch','abs');
INSERT INTO exercises VALUES(2207,'roller side lat stretch','lats');
INSERT INTO exercises VALUES(2208,'roller back stretch','spine');
INSERT INTO exercises VALUES(2209,'roller seated single leg shoulder flexor depresor retractor','pectorals');
INSERT INTO exercises VALUES(2271,'left hook. boxing','delts');
INSERT INTO exercises VALUES(2285,'lever pullover ','lats');
INSERT INTO exercises VALUES(2286,'lever hip extension v. 2','glutes');
INSERT INTO exercises VALUES(2287,'lever alternate leg press ','quads');
INSERT INTO exercises VALUES(2288,'lever gripper hands ','forearms');
INSERT INTO exercises VALUES(2289,'lever calf press ','calves');
INSERT INTO exercises VALUES(2292,'dumbbell rear delt raise','delts');
INSERT INTO exercises VALUES(2293,'dumbbell standing zottman preacher curl','biceps');
INSERT INTO exercises VALUES(2294,'dumbbell zottman preacher curl','biceps');
INSERT INTO exercises VALUES(2297,'stability ball crunch (full range hands behind head)','abs');
INSERT INTO exercises VALUES(2298,'inverted row on bench','upper back');
INSERT INTO exercises VALUES(2300,'inverted row bent knees','upper back');
INSERT INTO exercises VALUES(2311,'walking on stepmill','cardiovascular system');
INSERT INTO exercises VALUES(2312,'lying elbow to knee','abs');
INSERT INTO exercises VALUES(2315,'lever rotary calf','calves');
INSERT INTO exercises VALUES(2317,'dumbbell seated bent arm lateral raise','delts');
INSERT INTO exercises VALUES(2318,'lever shoulder press  v. 3','delts');
INSERT INTO exercises VALUES(2321,'dumbbell standing inner biceps curl v. 2','biceps');
INSERT INTO exercises VALUES(2327,'dumbbell reverse grip row (female)','upper back');
INSERT INTO exercises VALUES(2328,'narrow push-up on exercise ball','triceps');
INSERT INTO exercises VALUES(2329,'spine twist','abs');
INSERT INTO exercises VALUES(2330,'cable lat pulldown full range of motion','lats');
INSERT INTO exercises VALUES(2331,'cycle cross trainer','cardiovascular system');
INSERT INTO exercises VALUES(2333,'arm slingers hanging straight legs','abs');
INSERT INTO exercises VALUES(2334,'sled lying calf press','calves');
INSERT INTO exercises VALUES(2335,'lever seated calf press','calves');
INSERT INTO exercises VALUES(2355,'arm slingers hanging bent knee legs','abs');
INSERT INTO exercises VALUES(2363,'wide-grip chest dip on high parallel bars','pectorals');
INSERT INTO exercises VALUES(2364,'assisted wide-grip chest dip (kneeling)','pectorals');
INSERT INTO exercises VALUES(2368,'split squats','quads');
INSERT INTO exercises VALUES(2371,'weighted russian twist v. 2','abs');
INSERT INTO exercises VALUES(2397,'dumbbell scott press','delts');
INSERT INTO exercises VALUES(2398,'close-grip push-up (on knees)','triceps');
INSERT INTO exercises VALUES(2399,'cable seated twist','abs');
INSERT INTO exercises VALUES(2400,'inverse leg curl (on pull-up cable machine)','hamstrings');
INSERT INTO exercises VALUES(2401,'dumbbell biceps curl (with arm blaster)','biceps');
INSERT INTO exercises VALUES(2402,'dumbbell hammer curls (with arm blaster)','biceps');
INSERT INTO exercises VALUES(2403,'dumbbell alternate biceps curl (with arm blaster)','biceps');
INSERT INTO exercises VALUES(2404,'ez-bar biceps curl (with arm blaster)','biceps');
INSERT INTO exercises VALUES(2405,'cable triceps pushdown (v-bar) (with arm blaster)','triceps');
INSERT INTO exercises VALUES(2406,'cable reverse grip triceps pushdown (sz-bar) (with arm blaster)','triceps');
INSERT INTO exercises VALUES(2407,'barbell biceps curl (with arm blaster)','biceps');
INSERT INTO exercises VALUES(2414,'barbell standing concentration curl','biceps');
INSERT INTO exercises VALUES(2429,'frog crunch','abs');
INSERT INTO exercises VALUES(2432,'ez-bar close-grip bench press','triceps');
INSERT INTO exercises VALUES(2459,'tire flip','glutes');
INSERT INTO exercises VALUES(2462,'chest dip on straight bar','pectorals');
INSERT INTO exercises VALUES(2464,'cable thibaudeau kayak row','lats');
INSERT INTO exercises VALUES(2466,'bridge - mountain climber (cross body)','abs');
INSERT INTO exercises VALUES(2470,'dumbbell lying on floor rear delt raise','delts');
INSERT INTO exercises VALUES(2567,'seated piriformis stretch','glutes');
INSERT INTO exercises VALUES(2571,'rocking frog stretch','glutes');
INSERT INTO exercises VALUES(2611,'lever horizontal one leg press','glutes');
INSERT INTO exercises VALUES(2612,'jump rope','cardiovascular system');
INSERT INTO exercises VALUES(2616,'cable lateral pulldown with v-bar','lats');
INSERT INTO exercises VALUES(2705,'dumbbell lying pronation on floor','forearms');
INSERT INTO exercises VALUES(2706,'dumbbell lying supination on floor','forearms');
INSERT INTO exercises VALUES(2736,'lever reverse grip lateral pulldown ','lats');
INSERT INTO exercises VALUES(2741,'ez-barbell standing wide grip biceps curl','biceps');
INSERT INTO exercises VALUES(2796,'dumbbell step-up lunge','quads');
INSERT INTO exercises VALUES(2798,'barbell squat jump step rear lunge','quads');
INSERT INTO exercises VALUES(2799,'barbell sitted alternate leg raise','abs');
INSERT INTO exercises VALUES(2800,'barbell sitted alternate leg raise (female)','abs');
INSERT INTO exercises VALUES(2801,'twisted leg raise (female)','abs');
INSERT INTO exercises VALUES(2802,'twisted leg raise','abs');
INSERT INTO exercises VALUES(2803,'dumbbell supported squat','quads');
INSERT INTO exercises VALUES(2805,'dumbbell single leg deadlift with stepbox support','glutes');
INSERT INTO exercises VALUES(2808,'dumbbell sumo pull through','glutes');
INSERT INTO exercises VALUES(2810,'barbell split squat v. 2','quads');
INSERT INTO exercises VALUES(2812,'dumbbell step-up split squat','quads');
INSERT INTO exercises VALUES(2963,'captains chair straight leg raise','abs');
INSERT INTO exercises VALUES(2987,'weighted close grip chin-up on dip cage','lats');
INSERT INTO exercises VALUES(3006,'resistance band seated hip abduction','abductors');
INSERT INTO exercises VALUES(3007,'resistance band leg extension','quads');
INSERT INTO exercises VALUES(3010,'ez bar lying bent arms pullover','lats');
INSERT INTO exercises VALUES(3011,'incline scapula push up','serratus anterior');
INSERT INTO exercises VALUES(3012,'scapula dips','traps');
INSERT INTO exercises VALUES(3013,'low glute bridge on floor','glutes');
INSERT INTO exercises VALUES(3016,'curl-up','abs');
INSERT INTO exercises VALUES(3017,'barbell pendlay row','upper back');
INSERT INTO exercises VALUES(3019,'bench pull-ups','lats');
INSERT INTO exercises VALUES(3021,'scapula push-up','serratus anterior');
INSERT INTO exercises VALUES(3116,'band fixed back underhand pulldown','lats');
INSERT INTO exercises VALUES(3117,'band fixed back close grip pulldown','lats');
INSERT INTO exercises VALUES(3119,'potty squat','abs');
INSERT INTO exercises VALUES(3122,'resistance band seated shoulder press','delts');
INSERT INTO exercises VALUES(3123,'resistance band seated biceps curl','biceps');
INSERT INTO exercises VALUES(3124,'resistance band seated chest press','pectorals');
INSERT INTO exercises VALUES(3132,'potty squat with support','glutes');
INSERT INTO exercises VALUES(3142,'smith sumo squat','glutes');
INSERT INTO exercises VALUES(3144,'resistance band seated straight back row','upper back');
INSERT INTO exercises VALUES(3145,'push-up plus','pectorals');
INSERT INTO exercises VALUES(3147,'pelvic tilt','abs');
INSERT INTO exercises VALUES(3156,'bodyweight standing close-grip one arm row','upper back');
INSERT INTO exercises VALUES(3158,'bodyweight standing close-grip row','upper back');
INSERT INTO exercises VALUES(3161,'bodyweight standing one arm row (with towel)','upper back');
INSERT INTO exercises VALUES(3162,'bodyweight standing one arm row','upper back');
INSERT INTO exercises VALUES(3165,'bodyweight standing row (with towel)','upper back');
INSERT INTO exercises VALUES(3166,'bodyweight standing row','upper back');
INSERT INTO exercises VALUES(3167,'bodyweight squatting row (with towel)','upper back');
INSERT INTO exercises VALUES(3168,'bodyweight squatting row','upper back');
INSERT INTO exercises VALUES(3193,'glute-ham raise','hamstrings');
INSERT INTO exercises VALUES(3194,'frankenstein squat','glutes');
INSERT INTO exercises VALUES(3195,'lever lying two-one leg curl','hamstrings');
INSERT INTO exercises VALUES(3200,'lever bent-over row with v-bar ','upper back');
INSERT INTO exercises VALUES(3201,'quarter sit-up','abs');
INSERT INTO exercises VALUES(3202,'half sit-up (male)','abs');
INSERT INTO exercises VALUES(3203,'prisoner half sit-up (male)','abs');
INSERT INTO exercises VALUES(3204,'arms overhead full sit-up (male)','abs');
INSERT INTO exercises VALUES(3211,'kneeling push-up (male)','pectorals');
INSERT INTO exercises VALUES(3212,'basic toe touch (male)','glutes');
INSERT INTO exercises VALUES(3213,'side-to-side toe touch (male)','abs');
INSERT INTO exercises VALUES(3214,'arms apart circular toe touch (male)','glutes');
INSERT INTO exercises VALUES(3215,'hands reversed clasped circular toe touch (male)','glutes');
INSERT INTO exercises VALUES(3216,'chest tap push-up (male)','pectorals');
INSERT INTO exercises VALUES(3217,'modified hindu push-up (male)','pectorals');
INSERT INTO exercises VALUES(3218,'hands clasped circular toe touch (male)','glutes');
INSERT INTO exercises VALUES(3219,'scissor jumps (male)','cardiovascular system');
INSERT INTO exercises VALUES(3220,'astride jumps (male)','cardiovascular system');
INSERT INTO exercises VALUES(3221,'half knee bends (male)','cardiovascular system');
INSERT INTO exercises VALUES(3222,'semi squat jump (male)','cardiovascular system');
INSERT INTO exercises VALUES(3223,'star jump (male)','cardiovascular system');
INSERT INTO exercises VALUES(3224,'jack jump (male)','cardiovascular system');
INSERT INTO exercises VALUES(3231,'two toe touch (male)','spine');
INSERT INTO exercises VALUES(3234,'hyght dumbbell fly','pectorals');
INSERT INTO exercises VALUES(3235,'cable assisted inverse leg curl','hamstrings');
INSERT INTO exercises VALUES(3236,'resistance band hip thrusts on knees (female)','glutes');
INSERT INTO exercises VALUES(3237,'landmine lateral raise','delts');
INSERT INTO exercises VALUES(3239,'kneeling plank tap shoulder (male)','abs');
INSERT INTO exercises VALUES(3240,'exercise ball on the wall calf raise (tennis ball between knees)','calves');
INSERT INTO exercises VALUES(3241,'exercise ball on the wall calf raise (tennis ball between ankles)','calves');
INSERT INTO exercises VALUES(3281,'smith full squat','glutes');
INSERT INTO exercises VALUES(3286,'weighted muscle up','lats');
INSERT INTO exercises VALUES(3287,'elbow dips','triceps');
INSERT INTO exercises VALUES(3288,'korean dips','pectorals');
INSERT INTO exercises VALUES(3289,'impossible dips','triceps');
INSERT INTO exercises VALUES(3290,'weighted one hand pull up','lats');
INSERT INTO exercises VALUES(3291,'stalder press','triceps');
INSERT INTO exercises VALUES(3292,'elevator','upper back');
INSERT INTO exercises VALUES(3293,'archer pull up','lats');
INSERT INTO exercises VALUES(3294,'archer push up','pectorals');
INSERT INTO exercises VALUES(3295,'front lever reps','upper back');
INSERT INTO exercises VALUES(3296,'front lever','abs');
INSERT INTO exercises VALUES(3297,'back lever','upper back');
INSERT INTO exercises VALUES(3298,'straddle planche','abs');
INSERT INTO exercises VALUES(3299,'full planche','abs');
INSERT INTO exercises VALUES(3300,'lean planche','abs');
INSERT INTO exercises VALUES(3301,'frog planche','abs');
INSERT INTO exercises VALUES(3302,'handstand','triceps');
INSERT INTO exercises VALUES(3303,'flag','abs');
INSERT INTO exercises VALUES(3304,'skin the cat','upper back');
INSERT INTO exercises VALUES(3305,'barbell thruster','delts');
INSERT INTO exercises VALUES(3312,'weighted muscle up (on bar)','lats');
INSERT INTO exercises VALUES(3313,'weighted straight bar dip','pectorals');
INSERT INTO exercises VALUES(3314,'straddle maltese','abs');
INSERT INTO exercises VALUES(3315,'full maltese','abs');
INSERT INTO exercises VALUES(3318,'swing 360','cardiovascular system');
INSERT INTO exercises VALUES(3327,'full planche push-up','pectorals');
INSERT INTO exercises VALUES(3360,'bear crawl','cardiovascular system');
INSERT INTO exercises VALUES(3361,'skater hops','cardiovascular system');
INSERT INTO exercises VALUES(3418,'l-pull-up','lats');
INSERT INTO exercises VALUES(3419,'l-sit on floor','abs');
INSERT INTO exercises VALUES(3420,'v-sit on floor','abs');
INSERT INTO exercises VALUES(3433,'swimmer kicks v. 2 (male)','glutes');
INSERT INTO exercises VALUES(3470,'forward lunge (male)','glutes');
INSERT INTO exercises VALUES(3523,'glute bridge two legs on bench (male)','glutes');
INSERT INTO exercises VALUES(3533,'quads','quads');
INSERT INTO exercises VALUES(3541,'dumbbell incline y-raise','upper back');
INSERT INTO exercises VALUES(3542,'dumbbell incline t-raise','delts');
INSERT INTO exercises VALUES(3543,'bodyweight drop jump squat','glutes');
INSERT INTO exercises VALUES(3544,'bodyweight incline side plank','abs');
INSERT INTO exercises VALUES(3545,'dumbbell incline alternate press','pectorals');
INSERT INTO exercises VALUES(3546,'dumbbell seated alternate shoulder','delts');
INSERT INTO exercises VALUES(3547,'dumbbell seated biceps curl to shoulder press','biceps');
INSERT INTO exercises VALUES(3548,'dumbbell single arm overhead carry','delts');
INSERT INTO exercises VALUES(3552,'quick feet v. 2','quads');
INSERT INTO exercises VALUES(3560,'dumbbell standing alternate hammer curl and press','biceps');
INSERT INTO exercises VALUES(3561,'glute bridge march','glutes');
INSERT INTO exercises VALUES(3562,'barbell glute bridge two legs on bench (male)','glutes');
INSERT INTO exercises VALUES(3563,'cable one arm pulldown','lats');
INSERT INTO exercises VALUES(3582,'lunge with jump','glutes');
INSERT INTO exercises VALUES(3635,'dumbbell contralateral forward lunge','glutes');
INSERT INTO exercises VALUES(3636,'high knee against wall','cardiovascular system');
INSERT INTO exercises VALUES(3637,'wheel run','cardiovascular system');
INSERT INTO exercises VALUES(3638,'push to run','cardiovascular system');
INSERT INTO exercises VALUES(3639,'bent knee lying twist (male)','glutes');
INSERT INTO exercises VALUES(3640,'knee touch crunch','abs');
INSERT INTO exercises VALUES(3641,'weighted kneeling step with swing','delts');
INSERT INTO exercises VALUES(3642,'weighted stretch lunge','glutes');
INSERT INTO exercises VALUES(3643,'weighted cossack squats (male)','glutes');
INSERT INTO exercises VALUES(3644,'weighted lunge with swing','glutes');
INSERT INTO exercises VALUES(3645,'single leg bridge with outstretched leg','glutes');
INSERT INTO exercises VALUES(3655,'walking high knees lunge','cardiovascular system');
INSERT INTO exercises VALUES(3656,'short stride run','cardiovascular system');
INSERT INTO exercises VALUES(3662,'pike-to-cobra push-up','glutes');
INSERT INTO exercises VALUES(3663,'reverse plank with leg lift','abs');
INSERT INTO exercises VALUES(3664,'dumbbell side plank with rear fly','upper back');
INSERT INTO exercises VALUES(3665,'power point plank','abs');
INSERT INTO exercises VALUES(3666,'walking on incline treadmill','cardiovascular system');
INSERT INTO exercises VALUES(3667,'side lying hip adduction (male)','adductors');
INSERT INTO exercises VALUES(3669,'standing archer','upper back');
INSERT INTO exercises VALUES(3670,'weighted decline sit-up','abs');
INSERT INTO exercises VALUES(3671,'ski step','cardiovascular system');
INSERT INTO exercises VALUES(3672,'back and forth step','cardiovascular system');
INSERT INTO exercises VALUES(3679,'sit-up with arms on chest','abs');
INSERT INTO exercises VALUES(3697,'cable kneeling rear delt row (with rope) (male)','delts');
INSERT INTO exercises VALUES(3698,'inchworm v. 2','abs');
INSERT INTO exercises VALUES(3699,'shoulder tap','abs');
INSERT INTO exercises VALUES(3758,'lever standing chest press','pectorals');
INSERT INTO exercises VALUES(3759,'lever seated good morning','glutes');
INSERT INTO exercises VALUES(3760,'lever seated crunch v. 2','abs');
INSERT INTO exercises VALUES(3769,'curtsey squat','glutes');
INSERT INTO exercises VALUES(3785,'incline push-up (on box)','pectorals');
INSERT INTO exercises VALUES(3888,'dumbbell one arm snatch','glutes');
INSERT INTO exercises VALUES(5201,'dumbbell waiter biceps curl','biceps');
